import { createVuetify } from 'vuetify'
import {
  VAlert,
  VApp,
  VAppBar,
  VAppBarNavIcon,
  VAutocomplete,
  VAvatar,
  VBadge,
  VBanner,
  VBottomSheet,
  VBreadcrumbs,
  VBreadcrumbsItem,
  VBreadcrumbsDivider,
  VBtn,
  VBtnToggle,
  VCard,
  VCardActions,
  VCardItem,
  VCardSubtitle,
  VCardText,
  VCardTitle,
  VCheckbox,
  VChip,
  VCol,
  VContainer,
  VDataTable,
  VDatePicker,
  VDialog,
  VDivider,
  VExpandTransition,
  VFadeTransition,
  VExpansionPanel,
  VExpansionPanels,
  VExpansionPanelText,
  VExpansionPanelTitle,
  VFooter,
  VIcon,
  VImg,
  VList,
  VListItem,
  VListItemSubtitle,
  VListItemTitle,
  VMain,
  VMenu,
  VNavigationDrawer,
  VOverlay,
  VProgressCircular,
  VProgressLinear,
  VRadio,
  VRadioGroup,
  VRow,
  VSelect,
  VSheet,
  VSkeletonLoader,
  VSlider,
  VSnackbar,
  VSpacer,
  VSwitch,
  VTable,
  VTab,
  VTabs,
  VTabsWindow,
  VTabsWindowItem,
  VTextarea,
  VTextField,
  VToolbar,
  VToolbarItems,
  VToolbarTitle,
  VTooltip,
} from 'vuetify/components'
import '~/assets/variables.scss'

import * as directives from 'vuetify/directives'
import colors from 'vuetify/util/colors'

export default defineNuxtPlugin(nuxtApp => {
  const vuetify = createVuetify({
    ssr: true,
    components: {
      VApp,
      VMain,
      VContainer,
      VRow,
      VCol,
      VSpacer,
      VDivider,
      VAppBar,
      VAppBarNavIcon,
      VToolbar,
      VToolbarTitle,
      VToolbarItems,
      VNavigationDrawer,
      VFooter,
      VList,
      VListItem,
      VListItemTitle,
      VListItemSubtitle,
      VBtn,
      VBtnToggle,
      VIcon,
      VTextField,
      VTextarea,
      VAutocomplete,
      VSelect,
      VCheckbox,
      VSwitch,
      VMenu,
      VDatePicker,
      VSlider,
      VDataTable,
      VTable,
      VExpandTransition,
      VFadeTransition,
      VCard,
      VCardItem,
      VCardTitle,
      VCardSubtitle,
      VCardText,
      VCardActions,
      VChip,
      VAlert,
      VSnackbar,
      VImg,
      VAvatar,
      VBadge,
      VBreadcrumbs,
      VBreadcrumbsItem,
      VBreadcrumbsDivider,
      VTooltip,
      VProgressLinear,
      VProgressCircular,
      VTab,
      VTabs,
      VTabsWindow,
      VTabsWindowItem,
      VDialog,
      VSheet,
      VExpansionPanels,
      VExpansionPanel,
      VExpansionPanelTitle,
      VExpansionPanelText,
      VRadio,
      VRadioGroup,
      VBottomSheet,
      VBanner,
      VOverlay,
      VSkeletonLoader,
    },
    directives,
    theme: {
      // SSR + first paint default. The client theme plugin / `useThemeMode`
      // switches to the persisted or system preference after hydration.
      defaultTheme: 'dark',
      themes: {
        dark: {
          dark: true,
          colors: {
            // Deep navy canvas. Vuetify left .v-application painting white in dark
            // mode, which bled through transparent sections; an explicit background
            // keeps the whole app shell cohesively dark on every page.
            background: '#0a0e1a',
            surface: '#121a2e',
            primary: colors.blue.darken2,
            accent: '#FFFFFF',
            secondary: colors.amber.darken3,
            info: colors.teal.lighten1,
            warning: colors.amber.base,
            error: colors.deepOrange.accent4,
            success: colors.green.accent3,
            // Link/anchor color: light blue reads on dark surfaces. Paired with
            // the light theme's darker `link` so anchors clear AA in both modes.
            link: '#64b5f6',
          },
        },
        light: {
          dark: false,
          colors: {
            background: '#f6f7f9',
            surface: '#ffffff',
            primary: colors.blue.darken2,
            accent: colors.blue.accent2,
            secondary: colors.amber.darken4,
            info: colors.teal.darken1,
            warning: colors.amber.darken3,
            error: colors.deepOrange.darken1,
            success: colors.green.darken2,
            // Darker blue so links clear AA (4.5:1) on white/light surfaces.
            link: '#1565c0',
          },
        },
      },
    },
  })

  nuxtApp.vueApp.use(vuetify)
})
