import { createVuetify } from 'vuetify'
import {
  VAlert,
  // Layout components
  VApp,
  // Navigation components
  VAppBar,
  VAppBarNavIcon,
  VAutocomplete,
  VAvatar,
  VBadge,
  VBanner,
  VBottomSheet,
  VBreadcrumbs,
  VBreadcrumbsItem,
  VBreadcrumbsDivider,
  // Form components
  VBtn,
  VBtnToggle,
  VCard,
  VCardActions,
  VCardItem,
  VCardSubtitle,
  VCardText,
  VCardTitle,
  VCheckbox,
  VChip,
  VCol,
  VContainer,
  // Data display components
  VDataTable,
  VDatePicker,
  VDialog,
  VDivider,
  VExpandTransition,
  VFadeTransition,
  VExpansionPanel,
  VExpansionPanels,
  VExpansionPanelText,
  VExpansionPanelTitle,
  VFooter,
  VIcon,
  VImg,
  // List components
  VList,
  VListItem,
  VListItemSubtitle,
  VListItemTitle,
  VMain,
  VMenu,
  VNavigationDrawer,
  VOverlay,
  VProgressCircular,
  VProgressLinear,
  VRadio,
  VRadioGroup,
  VRow,
  VSelect,
  VSheet,
  VSkeletonLoader,
  VSlider,
  VSnackbar,
  VSpacer,
  VSwitch,
  VTable,
  // Other components
  VTab,
  VTabs,
  VTabsWindow,
  VTabsWindowItem,
  VTextarea,
  VTextField,
  VToolbar,
  VToolbarItems,
  VToolbarTitle,
  VTooltip,
} from 'vuetify/components'
import '~/assets/variables.scss'

import * as directives from 'vuetify/directives'
import colors from 'vuetify/util/colors'

export default defineNuxtPlugin(nuxtApp => {
  const vuetify = createVuetify({
    ssr: true,
    components: {
      VApp,
      VMain,
      VContainer,
      VRow,
      VCol,
      VSpacer,
      VDivider,
      VAppBar,
      VAppBarNavIcon,
      VToolbar,
      VToolbarTitle,
      VToolbarItems,
      VNavigationDrawer,
      VFooter,
      VList,
      VListItem,
      VListItemTitle,
      VListItemSubtitle,
      VBtn,
      VBtnToggle,
      VIcon,
      VTextField,
      VTextarea,
      VAutocomplete,
      VSelect,
      VCheckbox,
      VSwitch,
      VMenu,
      VDatePicker,
      VSlider,
      VDataTable,
      VTable,
      VExpandTransition,
      VFadeTransition,
      VCard,
      VCardItem,
      VCardTitle,
      VCardSubtitle,
      VCardText,
      VCardActions,
      VChip,
      VAlert,
      VSnackbar,
      VImg,
      VAvatar,
      VBadge,
      VBreadcrumbs,
      VBreadcrumbsItem,
      VBreadcrumbsDivider,
      VTooltip,
      VProgressLinear,
      VProgressCircular,
      VTab,
      VTabs,
      VTabsWindow,
      VTabsWindowItem,
      VDialog,
      VSheet,
      VExpansionPanels,
      VExpansionPanel,
      VExpansionPanelTitle,
      VExpansionPanelText,
      VRadio,
      VRadioGroup,
      VBottomSheet,
      VBanner,
      VOverlay,
      VSkeletonLoader,
    },
    directives,
    theme: {
      defaultTheme: 'dark',
      themes: {
        dark: {
          colors: {
            primary: colors.blue.darken2,
            accent: '#FFFF',
            secondary: colors.amber.darken3,
            info: colors.teal.lighten1,
            warning: colors.amber.base,
            error: colors.deepOrange.accent4,
            success: colors.green.accent3,
          },
        },
      },
    },
  })

  nuxtApp.vueApp.use(vuetify)
})
