// The channels /videos-de-economia-uruguay reads, curated by hand.
//
// EVERY `channelId` here was confirmed by fetching that channel's real Atom feed and reading the
// name and the publish dates that came back. That is not ceremony: a mistyped id does not fail, it
// returns YouTube's 404 page, and `refresh.ts` records the channel as down — one silent, permanent
// hole in the page that nobody would notice. `tests/videos/channels.test.ts` checks the shape;
// only a person with a feed in front of them can check the substance.
//
// What earns a place: the channel publishes, in Spanish, about something that touches a Uruguayan's
// pocket — the dollar, prices, wages, taxes, credit, housing, retirement, investing, importing.
// Uruguayan first and by a wide margin; a foreign channel has to be excellent to displace a local
// one on a page written for Uruguay, and the catalogue test fails if that balance ever tips.
//
// What is deliberately NOT here, having been read and rejected:
//   - channels that promise a return ("ganancias sin hacer nada"). This site tells people how to
//     compare a TEA; a video list that quietly recommends a yield product undoes that in one row.
//   - business-leadership and entrepreneur-interview channels (Líderes Empresariales, Corpo,
//     Pilares, Fuera de Zona). Good channels; they are about management, not about money.
//   - channels whose recent feed is all Shorts (URUCAP, Cámara de Industrias). `refresh.ts` drops
//     Shorts, so those entries would contribute an empty feed and a permanent zero on the page.
//   - institutional channels whose uploads are convocatorias and seminars rather than money
//     content (ANDE, OPP, FCEA, República AFAP), and agro/market channels (Valor Agregado) —
//     the site has no agro topic to file them under.
//
// To add one: find the channel id (`curl -sL https://www.youtube.com/@handle | grep -o
// 'channel_id=UC[A-Za-z0-9_-]*'`), read its feed
// (`curl -s "https://www.youtube.com/feeds/videos.xml?channel_id=UC…"`), and only then write the
// row — with `needsFilter: true` unless the WHOLE channel is about money.

import type { VideoChannel } from "./types";

export const VIDEO_CHANNELS: readonly VideoChannel[] = Object.freeze([
  // ---------------------------------------------------------------- Uruguay · economía y nada más
  {
    id: "neurona-financiera",
    channelId: "UCPmD-5y1a78hK6ADMZe0I_Q",
    name: "Rodrigo Álvarez - Neurona Financiera",
    handle: "@NeuronaFinancieraOK",
    country: "UY",
    kind: "creador",
    needsFilter: false,
    weight: 3,
    blurb:
      "Finanzas personales con el marco bancario y legal uruguayo: deuda, hipotecas, bancos y ahorro, en voseo y sin promesas de rentabilidad.",
  },
  {
    id: "neurona-news",
    channelId: "UCE6qFi3uDmbxTJqQutMdfLw",
    name: "Neurona News",
    handle: "@NeuronaNews",
    country: "UY",
    kind: "medio",
    needsFilter: false,
    weight: 3,
    blurb:
      "El resumen semanal de la economía uruguaya: dólar, Copom, AFAP, inflación y costo de la vivienda. Todo el canal es economía.",
  },
  {
    id: "financiera-mente",
    channelId: "UCt16RZgWCCv90coEqHXonBw",
    name: "Financiera-Mente",
    handle: "@FinancieraMente",
    country: "UY",
    kind: "creador",
    needsFilter: false,
    weight: 3,
    blurb:
      "Cómo armar una cartera desde Uruguay: brokers, ETFs, criptomonedas y qué pasa con tu plata si el intermediario quiebra.",
  },
  {
    id: "finanzas-gaston",
    channelId: "UC7e0Vos7HfCaq257UBc6f6g",
    name: "Gastón Pérez - Finanzas Personales",
    handle: "@finanzasgaston",
    country: "UY",
    kind: "creador",
    needsFilter: false,
    weight: 3,
    blurb:
      "Análisis financiero de decisiones concretas de un uruguayo, del auto eléctrico a los instrumentos que se pueden comprar acá.",
  },
  {
    id: "botija-inversor",
    channelId: "UCWz3rXERQJO2Ms3PDk3hCqA",
    name: "Botija Inversor",
    handle: "@BotijaInversor",
    country: "UY",
    kind: "creador",
    needsFilter: false,
    weight: 3,
    blurb: "Educación financiera para uruguayos que arrancan: hábitos, ahorro, presupuesto y cripto.",
  },
  {
    id: "estudio-contable-dmf",
    channelId: "UC4sQlwJ21-TOgwzzH-oGtzA",
    name: "Estudio Contable DMF",
    handle: "@EstudioContableDMF",
    country: "UY",
    kind: "creador",
    needsFilter: false,
    weight: 3,
    blurb:
      "Un estudio contable uruguayo explicando IRPF, IVA de servicios personales y las declaraciones juradas de DGI.",
  },
  {
    id: "exante",
    channelId: "UCqZz9PPfFASIgxbCehX3h5Q",
    name: "Exante Uruguay",
    handle: "@exanteuruguay",
    country: "UY",
    kind: "broker",
    needsFilter: false,
    weight: 3,
    blurb: "La consultora económica uruguaya: coyuntura, proyecciones y lectura de los datos macro.",
  },
  {
    id: "gletir",
    channelId: "UC59SRwXTjOC2QULv4Ceazyg",
    name: "Gletir Corredor de Bolsa",
    handle: "@gletircorredordebolsa",
    country: "UY",
    kind: "broker",
    needsFilter: false,
    weight: 3,
    blurb:
      "Corredor de bolsa uruguayo: bonos, obligaciones negociables y cómo se invierte desde el mercado local.",
  },
  {
    id: "cpa-ferrere",
    channelId: "UCh3LCbrFQcRgsOkQebCSJ7A",
    name: "CPA Ferrere",
    handle: "@CPAFerrere",
    country: "UY",
    kind: "institucion",
    needsFilter: false,
    weight: 3,
    blurb: "Reuniones de coyuntura económica y análisis tributario de una de las consultoras grandes.",
  },
  {
    id: "ceres",
    channelId: "UC-93r-Go3w15TiNHtYhKdAA",
    name: "CERES Uruguay",
    handle: "@ceresuruguay6980",
    country: "UY",
    kind: "institucion",
    needsFilter: false,
    weight: 3,
    blurb: "Centro de estudios económicos: actividad, empleo y competitividad, con datos propios.",
  },
  {
    id: "ced",
    channelId: "UCKp4MO61532tT7x5Gx0vj-A",
    name: "CED Uruguay",
    handle: "@ceduruguay",
    country: "UY",
    kind: "institucion",
    needsFilter: false,
    weight: 3,
    blurb: "Centro de Estudios para el Desarrollo: presupuesto, gasto público y política económica.",
  },
  {
    id: "academia-nacional-economia",
    channelId: "UCpcqNxU8b0wy29RAgY_g3_A",
    name: "Academia Nacional de Economía",
    handle: "@academianacionaldeeconomia65",
    country: "UY",
    kind: "institucion",
    needsFilter: false,
    weight: 3,
    blurb:
      "Conversatorios de economistas uruguayos sobre comercio, integración regional y política económica.",
  },
  {
    id: "bcu",
    channelId: "UC9fkm72wx-bBK-le5rYh2Fw",
    name: "Banco Central del Uruguay",
    handle: "@BCUUy",
    country: "UY",
    kind: "institucion",
    needsFilter: false,
    weight: 3,
    blurb: "La fuente: decisiones de política monetaria, informes y educación financiera del BCU.",
  },
  {
    id: "mef",
    channelId: "UCu6vr8WRDa_4vxKeZZS7sxg",
    name: "Ministerio de Economía y Finanzas",
    handle: "@DGSUruguay",
    country: "UY",
    kind: "institucion",
    needsFilter: false,
    weight: 3,
    blurb: "Presupuesto, rendición de cuentas y deuda pública, contados por quien los firma.",
  },
  {
    id: "dgi",
    channelId: "UCLC0XwdQMGIq7Ed56m5lqSw",
    name: "DGI Uruguay",
    handle: "@eFacturaDGIUruguay",
    country: "UY",
    kind: "institucion",
    needsFilter: false,
    weight: 3,
    blurb: "Instructivos oficiales de DGI: e-factura, declaraciones y los trámites que hay que hacer sí o sí.",
  },
  {
    id: "bps",
    channelId: "UCicmGqs5rcAft0iKQTG1Nxg",
    name: "BPS",
    handle: "@BPS_uy",
    country: "UY",
    kind: "institucion",
    needsFilter: false,
    weight: 3,
    blurb: "Jubilaciones, aportes y prestaciones explicados por el propio Banco de Previsión Social.",
  },
  {
    id: "ine",
    channelId: "UCVKp6bAT-JfruLq39qKsQyA",
    name: "INE Uruguay",
    handle: "@ine_uruguay",
    country: "UY",
    kind: "institucion",
    needsFilter: false,
    weight: 3,
    blurb: "Quien publica el IPC y los datos de empleo, presentando sus propias mediciones.",
  },
  {
    id: "mtss",
    channelId: "UCK6K9XHlSC7pReMKkSs3CKg",
    name: "Ministerio de Trabajo y Seguridad Social",
    handle: "@MinisteriodeTrabajouy",
    country: "UY",
    kind: "institucion",
    needsFilter: false,
    weight: 3,
    blurb: "Consejos de salarios, seguro de paro y derechos laborales, desde el organismo que los aplica.",
  },
  {
    id: "uruguay-xxi",
    channelId: "UC83kNYBacxK-aq_o0xBmYyg",
    name: "Uruguay XXI",
    handle: "@UruguayXXIGUB",
    country: "UY",
    kind: "institucion",
    needsFilter: false,
    weight: 3,
    blurb: "Exportaciones, inversión extranjera y comercio exterior, con los números del organismo.",
  },

  // ------------------------------------------------- Uruguay · generalistas (se filtran por tema)
  {
    id: "el-observador",
    channelId: "UCLvbVJDsVX4-qoyladIiVaQ",
    name: "El Observador",
    handle: "@ObservaUY",
    country: "UY",
    kind: "medio",
    needsFilter: true,
    weight: 2,
    blurb:
      "El diario uruguayo de economía y negocios. El canal es el streaming general y mezcla deporte y política, así que se filtra por tema.",
  },
  {
    id: "el-observador-radio",
    channelId: "UC-rI_XNppHJO-Ga4RW_CDKw",
    name: "El Observador 107.9",
    handle: "@ElObservador107.9",
    country: "UY",
    kind: "medio",
    needsFilter: true,
    weight: 2,
    blurb: "La radio de El Observador: entrevistas a economistas y a quienes toman las decisiones.",
  },
  {
    id: "la-diaria",
    channelId: "UCu0rrtxKLExB_fNSAJ_SU9A",
    name: "la diaria",
    handle: "@ladiaria_",
    country: "UY",
    kind: "medio",
    needsFilter: true,
    weight: 2,
    blurb: "Cobertura con foco en trabajo, salarios y presupuesto, desde el otro extremo del espectro.",
  },
  {
    id: "busqueda",
    channelId: "UCa2cus7gyarXD8049iaLHBg",
    name: "Búsqueda",
    handle: "@busquedaonline",
    country: "UY",
    kind: "medio",
    needsFilter: true,
    weight: 2,
    blurb: "El semanario que primero cuenta buena parte de lo que después discute el resto.",
  },
  {
    id: "el-pais",
    channelId: "UC3QAqpAruUVvqKuWOzmkItg",
    name: "El País Uruguay",
    handle: "@elpaisuy",
    country: "UY",
    kind: "medio",
    needsFilter: true,
    weight: 2,
    blurb: "El diario de mayor circulación; su sección económica cubre dólar, tarifas y consumo.",
  },
  {
    id: "en-perspectiva",
    channelId: "UCzj1iuImjo-Eb8JMELC1Jwg",
    name: "En Perspectiva",
    handle: "@EnPerspectiva",
    country: "UY",
    kind: "medio",
    needsFilter: true,
    weight: 2,
    blurb: "Las entrevistas largas de la mañana uruguaya, donde el tema económico se explica entero.",
  },
  {
    id: "sarandi-690",
    channelId: "UC0HcjuycMRw7SbZ7s4CnaGQ",
    name: "Sarandí 690",
    handle: "@sarandi690ok",
    country: "UY",
    kind: "medio",
    needsFilter: true,
    weight: 2,
    blurb: "Radio con mesas de análisis donde suelen sentarse los economistas de los institutos.",
  },
  {
    id: "radio-carve",
    channelId: "UCT7OlB7p6v7ttbd843HZTDg",
    name: "Radio Carve",
    handle: "@radiocarve850",
    country: "UY",
    kind: "medio",
    needsFilter: true,
    weight: 2,
    blurb: "Informativo radial con seguimiento diario de los datos de actividad y precios.",
  },
  {
    id: "del-sol",
    channelId: "UCwxfiP2WBmLEblsrGgwWNMA",
    name: "DelSol 99.5 FM",
    handle: "@DelSolUy",
    country: "UY",
    kind: "medio",
    needsFilter: true,
    weight: 2,
    blurb: "Radio generalista que discute los temas de bolsillo en clave de conversación, no de informe.",
  },
  {
    id: "canal-5",
    channelId: "UCMHQqhtbpxfcnPPYpryapHA",
    name: "Canal 5 Uruguay",
    handle: "@Canal5UY",
    country: "UY",
    kind: "medio",
    needsFilter: true,
    weight: 2,
    blurb: "La televisión pública: coberturas completas de anuncios oficiales y datos económicos.",
  },
  {
    id: "canal-4",
    channelId: "UCp6X5jzfmwbOeclRArOi18g",
    name: "Canal 4",
    handle: "@Canal4uy",
    country: "UY",
    kind: "medio",
    needsFilter: true,
    weight: 2,
    blurb: "Informativo de aire con las notas de consumo, tarifas y trabajo que llegan a más gente.",
  },
  {
    id: "vtv-noticias",
    channelId: "UCdW5hWEhQqexGEApXjBqQrQ",
    name: "VTV Noticias",
    handle: "@vtvnoticias8652",
    country: "UY",
    kind: "medio",
    needsFilter: true,
    weight: 2,
    blurb: "Informativo del cable, con notas largas sobre precios, aduana y comercio de frontera.",
  },
  {
    id: "impo",
    channelId: "UCKvCkJ2May2MuoHtRIxH1UQ",
    name: "IMPO",
    handle: "@ImpoUy",
    country: "UY",
    kind: "institucion",
    needsFilter: true,
    weight: 2,
    blurb:
      "El Diario Oficial en video, día por día: cuando una norma cambia un impuesto o un tope, sale acá primero.",
  },
  {
    id: "itau-uruguay",
    channelId: "UCXNw6kHnQh-aviXssXt6JDw",
    name: "Itaú Uruguay",
    handle: "@itauuruguay",
    country: "UY",
    kind: "institucion",
    needsFilter: true,
    weight: 2,
    blurb:
      "Un banco de plaza. Publica material propio sobre cambios tributarios e inversiones, mezclado con su publicidad — de ahí el filtro.",
  },
  {
    id: "adm-uruguay",
    channelId: "UCLHGLgAY2hIvI13xzEtrPQA",
    name: "ADM Uruguay",
    handle: "@ADMUruguay",
    country: "UY",
    kind: "institucion",
    needsFilter: true,
    weight: 2,
    blurb: "Los almuerzos donde ministros y economistas dicen en público lo que van a hacer.",
  },
  {
    id: "empresarios-de-aca",
    channelId: "UCE3K5h_aLAF9TKaVKbEeuLg",
    name: "Empresarios de Acá",
    handle: "@empresariosdeaca",
    country: "UY",
    kind: "podcast",
    needsFilter: true,
    weight: 2,
    blurb: "El lado empleador de las discusiones de jornada, salarios y costos de contratar.",
  },

  // ------------------------------------------------------------------------- Afuera, en español
  {
    id: "bloomberg-linea",
    channelId: "UCt4iMhUHxnKfxJXIW36Y4Rw",
    name: "Bloomberg Línea",
    handle: "@bloomberglinea",
    country: "REGIONAL",
    kind: "medio",
    needsFilter: false,
    weight: 2,
    blurb:
      "Bloomberg con redacción propia en América Latina: dólar, tasas y mercados de la región, sin promesas de rentabilidad.",
  },
  {
    id: "bloomberg-espanol",
    channelId: "UCp6zvh6_oW2pXbk0gPSjzyg",
    name: "Bloomberg en Español",
    handle: "@bloomberg_espanol",
    country: "REGIONAL",
    kind: "medio",
    needsFilter: false,
    weight: 1,
    blurb: "La señal en español de Bloomberg: mercados globales y su efecto sobre las economías chicas.",
  },
  {
    id: "el-cronista",
    channelId: "UCZi6C9-a4fYKiBoIuEJ80ZA",
    name: "El Cronista",
    handle: "@Cronista_ar",
    country: "AR",
    kind: "medio",
    needsFilter: true,
    weight: 1,
    blurb: "El diario económico argentino: sirve para entender el dólar del otro lado del río.",
  },
  {
    id: "juan-ramon-rallo",
    channelId: "UCBLCvUUCiSqBCEc-TqZ9rGw",
    name: "Juan Ramón Rallo",
    handle: "@juanrallo",
    country: "ES",
    kind: "creador",
    needsFilter: false,
    weight: 1,
    blurb: "Teoría económica explicada en largo, con una posición declarada y argumentada.",
  },
  {
    id: "visual-economik",
    channelId: "UC5HdVtarytnZi4eLogHAfoQ",
    name: "VisualEconomik",
    handle: "@VisualEconomik",
    country: "ES",
    kind: "creador",
    needsFilter: false,
    weight: 1,
    blurb: "Divulgación económica de país por país, útil para el contexto que ningún informativo da.",
  },
  {
    id: "value-school",
    channelId: "UCpLie5obXFdf8T0NG-IRHsA",
    name: "Value School",
    handle: "@ValueSchool",
    country: "ES",
    kind: "podcast",
    needsFilter: false,
    weight: 1,
    blurb: "Inversión a largo plazo y educación financiera, sin producto propio que vender en cámara.",
  },
  {
    id: "inversion-racional",
    channelId: "UCcyKcWVyR-SiQxQhfKSPzNw",
    name: "Inversión Racional",
    handle: "@InversionRacional",
    country: "ES",
    kind: "podcast",
    needsFilter: false,
    weight: 1,
    blurb: "Carteras, costos y sesgos, con el foco puesto en lo que el inversor sí controla.",
  },
  {
    id: "pequeno-cerdo-capitalista",
    channelId: "UCHMSzZaVrEjK35aYK3J7Htw",
    name: "Pequeño Cerdo Capitalista",
    handle: "@pequenocerdocapitalista",
    country: "MX",
    kind: "creador",
    needsFilter: false,
    weight: 1,
    blurb: "Finanzas personales para quien arranca de cero. Las cuentas son mexicanas; el método sirve igual.",
  },
  {
    id: "ivan-carrino",
    channelId: "UC5rplT0uwszhQLyNympTi_g",
    name: "Iván Carrino",
    handle: "@ivancarrinoOK",
    country: "AR",
    kind: "creador",
    needsFilter: false,
    weight: 1,
    blurb: "Inflación y política monetaria vistas desde Argentina, donde el tema se vive antes.",
  },
  {
    id: "fernando-marull",
    channelId: "UCcmZ6O6heqrURd0jI7nSy-g",
    name: "Fernando Marull",
    handle: "@FernandoMarull",
    country: "AR",
    kind: "creador",
    needsFilter: false,
    weight: 1,
    blurb: "Análisis de coyuntura y tipo de cambio de un economista de mercado, con los datos a la vista.",
  },
]);
