// What an empty home needs, in the order it needs it.
//
// THE ARRAY ORDER IS THE HARVEST PRIORITY. MercadoLibre and Facebook are searched per term, so a
// run that hits its query budget stops partway down this list — which is why the fridge, the
// washing machine and the mattress are at the top and the tea towels are at the bottom. A cut has
// to cost the cheap tail, never the line that decides the total.
//
// It is also the match order: the first category whose `include` accepts a title claims it. That
// works out because the expensive things have unambiguous names ("heladera", "lavarropas") and the
// collisions all live among the cheap ones ("mesa", "vaso"), which come later.
//
// The tier is NECESSITY, not price and not popularity: S means the house does not work without it,
// C means it can wait months. Every category says why in `reason`, and that text is published next
// to the row — a tier that cannot explain itself is just an opinion with a letter on it.
import type { EquiparCategory } from "./types";

/**
 * Dropped before any category is consulted. A fridge magnet is not a fridge, a door gasket is not
 * an oven, and Marketplace is full of "no funciona, para repuesto" at a tenth of the real price —
 * which would land squarely in the used band and drag the whole saving figure with it.
 */
export const NOT_A_PRODUCT =
  /\b(funda|fundas|repuesto|repuestos|filtro|filtros|soporte|adaptador|cable|control remoto|manija|bisagra|rueda|ruedas|tapa|tapas|juguete|miniatura|casa de munecas|sticker|vinilo|iman|imanes|calcomania|termostato|resistencia|correa|kit de reparacion|manual|display|placa|modulo|sensor|valvula|burlete|goma de puerta|molde|muestra|alquiler|alquilo|permuta|reparacion|service|arreglo|no funciona|a reparar|para repuesto|para desarme|chatarra)\b/;

export const EQUIPAR_CATEGORIES: EquiparCategory[] = [
  // ---------------------------------------------------------------- grandes, tier S
  {
    key: "heladera",
    label: "Heladera",
    room: "cocina",
    tier: "S",
    regime: "modelo",
    reason:
      "Sin heladera no se puede guardar comida más de un día, así que define cuánto gastás en comer. Es la primera compra de una casa vacía y la más cara del tier S.",
    usedOk: true,
    usedNote: "Usada conviene, pero pedí verla enfriando: el compresor es lo que se muere y no se ve en la foto.",
    variants: [
      { key: "frigobar", label: "Frigobar (hasta 120 L)", numeric: { unit: "litros", min: 1, max: 129 }, rank: 1 },
      { key: "media", label: "Media (130 a 330 L)", numeric: { unit: "litros", min: 130, max: 330 }, fallback: true, rank: 2 },
      { key: "grande", label: "Grande (más de 330 L)", numeric: { unit: "litros", min: 331, max: 900 }, rank: 3 },
    ],
    include: /\b(heladera|refrigerador|frigobar)\b/,
    exclude: /\b(conservadora|portatil|de auto|12v|vinos|cervecera|exhibidora|mostrador|carnicer)\b/,
    urlHint: /(heladera|frigobar|refrigerador)/i,
    storeQueries: ["heladera", "heladeras", "frigobar"],
    mlQueries: ["heladera", "heladera con freezer", "frigobar", "heladera no frost"],
    fbQueries: ["heladera", "frigobar"],
  },
  {
    key: "colchon",
    label: "Colchón",
    room: "dormitorio",
    tier: "S",
    regime: "modelo",
    reason:
      "Se duerme todos los días desde el primero. Es el ítem donde comprar barato sale más caro: un colchón malo se hunde en un año y se paga de nuevo.",
    usedOk: false,
    usedNote:
      "Es la única compra de esta lista donde el usado no se recomienda: chinches, ácaros y un hundimiento que no se ve hasta que dormís encima.",
    variants: [
      { key: "1plaza", label: "1 plaza (90 cm)", match: /\b(1|una) ?plaza\b|\b90 ?x ?1|\b80 ?x ?1/, rank: 1 },
      { key: "2plazas", label: "2 plazas (140 cm)", match: /\b(2|dos) ?plazas?\b|\b140 ?x ?1|\b130 ?x ?1/, fallback: true, rank: 2 },
      { key: "queen", label: "Queen o King (160 cm+)", match: /\b(queen|king)\b|\b16[05] ?x ?[12]|\b18[05] ?x ?[12]|\b200 ?x ?200/, rank: 3 },
    ],
    include: /\bcolchon(es)?\b/,
    exclude: /\b(inflable|de aire|para bebe|cuna|corralito|camping|yoga|antiescara|sofa cama|para perro|mascota|topper|cubre)\b/,
    urlHint: /colchon/i,
    storeQueries: ["colchon", "colchones"],
    mlQueries: ["colchon 2 plazas", "colchon 1 plaza", "colchon queen", "colchon resortes"],
    fbQueries: ["colchon"],
  },
  {
    key: "lavarropas",
    label: "Lavarropas",
    room: "limpieza",
    tier: "A",
    regime: "modelo",
    reason:
      "Se puede lavar a mano o pagar lavadero unas semanas, así que no es del primer día — pero a los dos meses ya se pagó solo. Es la compra grande que sigue a la heladera.",
    usedOk: true,
    usedNote: "Usado es común y sano; pedí verlo centrifugando, que es donde aparecen los rulemanes gastados.",
    variants: [
      { key: "superior", label: "Carga superior", match: /\b(carga )?superior\b|\btop load\b/, rank: 1 },
      { key: "frontal", label: "Carga frontal", match: /\b(carga )?frontal\b|\bfront load\b/, fallback: true, rank: 2 },
    ],
    include: /\b(lavarropas|lavadora|lavasecarropas)\b/,
    exclude: /\b(secarropas|semi ?automatic|para bebe|de juguete|industrial)\b/,
    urlHint: /(lavarropas|lavadora)/i,
    storeQueries: ["lavarropas", "lavadora"],
    mlQueries: ["lavarropas", "lavarropas automatico", "lavarropas carga frontal"],
    fbQueries: ["lavarropas"],
  },
  {
    key: "cocina",
    label: "Cocina o anafe",
    room: "cocina",
    tier: "S",
    regime: "modelo",
    reason:
      "Cocinar en casa es la diferencia más grande entre un presupuesto que cierra y uno que no. Si el alquiler ya trae cocina, alcanza con un anafe y el gasto baja diez veces.",
    usedOk: true,
    usedNote: "El supergas de la garrafa de 13 kg tiene precio regulado y va aparte: no se compra con la cocina.",
    variants: [
      { key: "anafe", label: "Anafe (2 hornallas)", match: /\banafe\b|\b2 hornallas\b/, rank: 1 },
      { key: "cocina4", label: "Cocina 4 hornallas con horno", match: /\b(4|cuatro) hornallas\b|\bcon horno\b/, fallback: true, rank: 2 },
    ],
    include: /\b(anafe|cocina (a )?(gas|electrica|supergas)|cocina \d ?hornallas|hornalla)\b/,
    exclude: /\b(mueble|bajo mesada|alacena|campana|isla|juguete|de juguete|libro|curso)\b/,
    urlHint: /(anafe|cocina|hornalla)/i,
    storeQueries: ["anafe", "cocina", "hornallas"],
    mlQueries: ["cocina a gas", "anafe", "cocina 4 hornallas"],
    fbQueries: ["cocina a gas", "anafe"],
  },
  {
    key: "calefon",
    label: "Calefón",
    room: "bano",
    tier: "S",
    regime: "modelo",
    reason:
      "Agua caliente. Muchos alquileres ya lo traen instalado; cuando no, es del primer día y no hay sustituto razonable.",
    usedOk: true,
    variants: [
      { key: "50l", label: "50 litros", numeric: { unit: "litros", min: 1, max: 59 }, rank: 1 },
      { key: "80l", label: "80 litros", numeric: { unit: "litros", min: 60, max: 89 }, fallback: true, rank: 2 },
      { key: "100l", label: "100 litros o más", numeric: { unit: "litros", min: 90, max: 400 }, rank: 3 },
    ],
    include: /\b(calefon|calefones|termotanque)\b/,
    exclude: /\b(solar|a gas de paso|instalacion)\b/,
    urlHint: /(calefon|termotanque)/i,
    storeQueries: ["calefon", "termotanque"],
    mlQueries: ["calefon", "calefon 80 litros", "termotanque"],
    fbQueries: ["calefon"],
  },
  {
    key: "microondas",
    label: "Microondas",
    room: "cocina",
    tier: "A",
    regime: "modelo",
    reason:
      "No reemplaza a la cocina, pero recalentar y descongelar sin encender una hornalla cambia la rutina de quien come solo. De las primeras semanas, no del primer día.",
    usedOk: true,
    variants: [
      { key: "chico", label: "Hasta 23 L", numeric: { unit: "litros", min: 1, max: 23 }, fallback: true, rank: 1 },
      { key: "grande", label: "24 L o más", numeric: { unit: "litros", min: 24, max: 90 }, rank: 2 },
    ],
    include: /\b(microondas|micro ?ondas)\b/,
    exclude: /\b(bandeja|plato giratorio|grill de repuesto)\b/,
    urlHint: /microondas/i,
    storeQueries: ["microondas"],
    mlQueries: ["microondas", "microondas digital"],
    fbQueries: ["microondas"],
  },
  {
    key: "tv",
    label: "Televisor",
    room: "living",
    tier: "B",
    regime: "modelo",
    reason:
      "Nada en la casa deja de funcionar sin televisor, y hoy compite con un celular. Entra cuando ya está lo demás.",
    usedOk: true,
    variants: [
      { key: "32", label: '32 pulgadas', numeric: { unit: "pulgadas", min: 20, max: 39 }, fallback: true, rank: 1 },
      { key: "43", label: '43 pulgadas', numeric: { unit: "pulgadas", min: 40, max: 49 }, rank: 2 },
      { key: "55", label: '55 pulgadas o más', numeric: { unit: "pulgadas", min: 50, max: 90 }, rank: 3 },
    ],
    include: /\b(smart ?tv|televisor|television|led tv)\b/,
    exclude: /\b(monitor|proyector|decodificador|antena|rack|mesa para tv|box|chromecast)\b/,
    urlHint: /(televisor|smart-?tv|tv-)/i,
    storeQueries: ["televisor", "smart tv"],
    mlQueries: ["smart tv", "televisor 32", "televisor 43"],
    fbQueries: ["smart tv", "televisor"],
  },
  {
    key: "aire-acondicionado",
    label: "Aire acondicionado",
    room: "living",
    tier: "B",
    regime: "modelo",
    reason:
      "Frío en enero y calor en julio. Se sobrevive sin él —hay ventilador y estufa más abajo, mucho más baratos—, pero es la compra que más cambia la casa cuando hay resto. Además deshumidifica, así que reemplaza al deshumidificador del tier C.",
    usedOk: true,
    usedNote: "Sumale la instalación: no es un electrodoméstico que se enchufa.",
    variants: [
      { key: "12000", label: "12.000 BTU", numeric: { unit: "btu", min: 1000, max: 12999 }, fallback: true, rank: 1 },
      { key: "18000", label: "18.000 BTU o más", numeric: { unit: "btu", min: 13000, max: 40000 }, rank: 2 },
    ],
    include: /\b(aire acondicionado|split|aire split)\b/,
    exclude: /\b(portatil de aire|caño|instalacion|soporte|bomba)\b/,
    urlHint: /(aire-acondicionado|split)/i,
    storeQueries: ["aire acondicionado", "split"],
    mlQueries: ["aire acondicionado split", "aire acondicionado 12000"],
    fbQueries: ["aire acondicionado"],
  },
  // ---------------------------------------------------------------- muebles
  {
    key: "ropero",
    label: "Ropero o placard",
    room: "dormitorio",
    tier: "A",
    regime: "commodity",
    reason:
      "La ropa en cajas contra la pared funciona una semana y después no. Muchos alquileres ya traen placard armado; cuando no, es de las primeras semanas.",
    usedOk: true,
    variants: [
      { key: "2puertas", label: "2 puertas", match: /\b2 puertas\b|\bdos puertas\b/, fallback: true, rank: 1 },
      { key: "3puertas", label: "3 puertas o más", match: /\b[3-6] puertas\b|\btres puertas\b/, rank: 2 },
    ],
    include: /\b(ropero|placard|guardarropas)\b/,
    exclude: /\b(organizador|colgante|de tela|zapatero|barral|puerta de repuesto|bebe)\b/,
    urlHint: /(ropero|placard)/i,
    storeQueries: ["ropero", "placard"],
    mlQueries: ["ropero", "placard 2 puertas"],
    fbQueries: ["ropero", "placard"],
  },
  {
    key: "mesa-sillas",
    label: "Mesa con sillas",
    room: "living",
    tier: "A",
    regime: "commodity",
    reason:
      "Comer parado sobre la mesada se banca unos días. También es el único lugar de la casa para trabajar o recibir a alguien.",
    usedOk: true,
    variants: [
      { key: "4sillas", label: "Mesa con 4 sillas", match: /\b4 sillas\b|\bcuatro sillas\b/, fallback: true, rank: 1 },
      { key: "6sillas", label: "Mesa con 6 sillas", match: /\b6 sillas\b|\bseis sillas\b/, rank: 2 },
    ],
    include: /\b(juego de comedor|mesa (de )?comedor|mesa con \d sillas|mesa \+ ?\d sillas)\b/,
    exclude: /\b(de luz|ratona|de centro|para tv|de planchar|plegable de camping|escritorio|mantel|vidrio de repuesto)\b/,
    urlHint: /(comedor|mesa)/i,
    storeQueries: ["juego de comedor", "mesa comedor"],
    mlQueries: ["juego de comedor", "mesa con 4 sillas"],
    fbQueries: ["juego de comedor", "mesa y sillas"],
  },
  {
    key: "sofa",
    label: "Sofá",
    room: "living",
    tier: "B",
    regime: "commodity",
    reason: "Comodidad pura. La casa funciona entera sin sofá y es voluminoso de mudar, así que puede esperar.",
    usedOk: true,
    variants: [
      { key: "2cuerpos", label: "2 cuerpos", match: /\b2 cuerpos\b|\bdos cuerpos\b|\bloveseat\b/, fallback: true, rank: 1 },
      { key: "3cuerpos", label: "3 cuerpos o esquinero", match: /\b3 cuerpos\b|\btres cuerpos\b|\besquinero\b|\bchaise\b/, rank: 2 },
    ],
    include: /\b(sofa|sillon de living|futon|sofa cama)\b/,
    exclude: /\b(de oficina|gamer|escritorio|para bebe|inflable|puff|reclinable individual|de exterior)\b/,
    urlHint: /(sofa|futon|sillon)/i,
    storeQueries: ["sofa", "futon"],
    mlQueries: ["sofa 3 cuerpos", "sofa cama", "futon"],
    fbQueries: ["sofa", "futon"],
  },
  // ---------------------------------------------------------------- cocina chica
  {
    key: "olla",
    label: "Olla",
    room: "cocina",
    tier: "S",
    regime: "commodity",
    reason:
      "Hervir agua, hacer arroz, fideos o un guiso cubre la mayoría de lo que se cocina en una casa. Pocas y buenas antes que muchas y malas: el fondo fino quema todo y no se arregla.",
    usedOk: true,
    quantity: 2,
    variants: [
      { key: "chica", label: "16 a 18 cm", numeric: { unit: "cm", min: 10, max: 18 }, rank: 1 },
      { key: "media", label: "20 a 22 cm", numeric: { unit: "cm", min: 19, max: 22 }, fallback: true, rank: 2 },
      { key: "grande", label: "24 cm o más", numeric: { unit: "cm", min: 23, max: 40 }, rank: 3 },
    ],
    include: /\b(olla|ollas|cacerola|cacerolas|caldero)\b/,
    exclude: /\b(a presion de repuesto|electrica|arrocera|de juguete|para perro|de barro decorativa)\b/,
    urlHint: /(olla|cacerola)/i,
    storeQueries: ["olla", "ollas", "cacerola"],
    mlQueries: ["olla acero inoxidable", "juego de ollas", "cacerola"],
    fbQueries: ["ollas"],
  },
  {
    key: "sarten",
    label: "Sartén",
    room: "cocina",
    tier: "S",
    regime: "commodity",
    reason:
      "Un huevo, una milanesa, cualquier salteado. Es la pieza que más se usa y la que más rápido se arruina si es barata.",
    usedOk: true,
    quantity: 1,
    variants: [
      { key: "20", label: "20 a 22 cm", numeric: { unit: "cm", min: 10, max: 22 }, rank: 1 },
      { key: "24", label: "24 a 26 cm", numeric: { unit: "cm", min: 23, max: 26 }, fallback: true, rank: 2 },
      { key: "28", label: "28 cm o más", numeric: { unit: "cm", min: 27, max: 40 }, rank: 3 },
    ],
    include: /\b(sarten|sartenes|wok|paellera)\b/,
    exclude: /\b(electric|de juguete|mango de repuesto)\b/,
    urlHint: /(sarten|wok)/i,
    storeQueries: ["sarten", "sartenes"],
    mlQueries: ["sarten antiadherente", "sarten 24", "wok"],
    fbQueries: ["sarten"],
  },
  {
    key: "cuchillo",
    label: "Cuchillo de cocina",
    room: "cocina",
    tier: "S",
    regime: "commodity",
    reason:
      "Uno bueno reemplaza a seis malos. Es el utensilio con la mejor relación entre lo que cuesta y lo que cambia cocinar todos los días.",
    usedOk: false,
    quantity: 1,
    variants: [
      { key: "chef", label: "Cuchillo de cocina 20 cm", fallback: true, rank: 1 },
      { key: "juego", label: "Juego de cuchillos", match: /\b(juego|set)\b/, rank: 2 },
    ],
    include: /\b(cuchillo|cuchillos)\b/,
    exclude: /\b(de caza|tactico|carnicero industrial|electrico|de juguete|afilador|para pan de repuesto|cortapluma)\b/,
    urlHint: /cuchillo/i,
    storeQueries: ["cuchillo", "cuchillos"],
    mlQueries: ["cuchillo de cocina", "juego de cuchillos"],
    fbQueries: ["cuchillos cocina"],
  },
  {
    key: "cubiertos",
    label: "Cubiertos",
    room: "cocina",
    tier: "S",
    regime: "commodity",
    reason: "Comer. Un juego de 24 piezas cubre a cualquiera y no se vuelve a comprar en años.",
    usedOk: true,
    quantity: 1,
    variants: [
      { key: "servicio6", label: "Servicio para 6 (24 piezas)", fallback: true, rank: 1 },
      { key: "servicio12", label: "Servicio para 12 (48 piezas)", numeric: { unit: "piezas", min: 40, max: 100 }, rank: 2 },
    ],
    include: /\b(cubiertos|cubierteria|juego de cubiertos)\b/,
    exclude: /\b(de juguete|descartable|plastico descartable|para bebe|organizador|cubiertera)\b/,
    urlHint: /cubierto/i,
    storeQueries: ["cubiertos", "cubierteria"],
    mlQueries: ["juego de cubiertos", "cubiertos acero inoxidable"],
    fbQueries: ["cubiertos"],
  },
  {
    key: "vajilla",
    label: "Platos",
    room: "cocina",
    tier: "S",
    regime: "commodity",
    reason: "Comer. Lo mismo que los cubiertos, y por las mismas razones.",
    usedOk: true,
    quantity: 1,
    variants: [
      { key: "servicio6", label: "Vajilla para 6", fallback: true, rank: 1 },
      { key: "servicio12", label: "Vajilla para 12", numeric: { unit: "piezas", min: 30, max: 100 }, rank: 2 },
    ],
    include: /\b(vajilla|juego de platos|set de platos|plato playo|plato hondo)\b/,
    exclude: /\b(descartable|de juguete|decorativo|de pared|colgante|para bebe)\b/,
    urlHint: /(vajilla|plato)/i,
    storeQueries: ["vajilla", "platos"],
    mlQueries: ["juego de vajilla", "set de platos"],
    fbQueries: ["vajilla"],
  },
  {
    key: "vasos",
    label: "Vasos",
    room: "cocina",
    tier: "S",
    regime: "commodity",
    reason: "Tomar agua. Barato, imprescindible y de lo primero que se rompe, así que se compra de a set.",
    usedOk: true,
    quantity: 1,
    variants: [
      { key: "set6", label: "Set de 6", fallback: true, rank: 1 },
      { key: "set12", label: "Set de 12", numeric: { unit: "piezas", min: 10, max: 40 }, rank: 2 },
    ],
    include: /\b(vaso|vasos|set de vasos|juego de vasos)\b/,
    exclude: /\b(termico de auto|de juguete|descartable|medidor|de precipitado|termo|copa de vino)\b/,
    urlHint: /vaso/i,
    storeQueries: ["vasos", "juego de vasos"],
    mlQueries: ["juego de vasos", "set de vasos vidrio"],
    fbQueries: ["vasos"],
  },
  {
    key: "tabla-picar",
    label: "Tabla de picar",
    room: "cocina",
    tier: "A",
    regime: "commodity",
    reason:
      "De madera o bambú, no de metal ni de vidrio: la superficie dura le come el filo al cuchillo, y el cuchillo cuesta más que la tabla. Cuanto más gruesa, menos se tuerce.",
    usedOk: false,
    quantity: 1,
    variants: [{ key: "madera", label: "Madera o bambú", fallback: true, rank: 1 }],
    include: /\b(tabla de picar|tabla de cocina|tabla para cortar)\b/,
    exclude: /\b(de vidrio|de metal|de acero|de marmol|de juguete|de planchar|de surf)\b/,
    urlHint: /tabla/i,
    storeQueries: ["tabla de picar"],
    mlQueries: ["tabla de picar madera", "tabla de picar bambu"],
    fbQueries: ["tabla de picar"],
  },
  {
    key: "escurridor",
    label: "Escurridor de platos",
    room: "cocina",
    tier: "A",
    regime: "commodity",
    reason: "Sin él, la pila mojada ocupa la mesada entera. Barato y resuelve un problema diario.",
    usedOk: true,
    quantity: 1,
    variants: [{ key: "estandar", label: "Estándar", fallback: true, rank: 1 }],
    include: /\b(escurridor|secaplatos|escurreplatos)\b/,
    exclude: /\b(de ensalada|de pastas|para fregadero de repuesto)\b/,
    urlHint: /(escurridor|secaplatos)/i,
    storeQueries: ["escurridor", "secaplatos"],
    mlQueries: ["escurridor de platos", "secaplatos"],
    fbQueries: ["escurridor de platos"],
  },
  {
    key: "pava",
    label: "Pava o caldera",
    room: "cocina",
    tier: "B",
    regime: "commodity",
    reason:
      "En Uruguay se usa todos los días, pero una olla hierve agua igual. La eléctrica es comodidad, no necesidad.",
    usedOk: true,
    quantity: 1,
    variants: [
      { key: "comun", label: "Pava común", fallback: true, rank: 1 },
      { key: "electrica", label: "Pava eléctrica", match: /\belectrica\b/, rank: 2 },
    ],
    include: /\b(pava|caldera|hervidor|jarra electrica)\b/,
    exclude: /\b(de calefaccion|a lena|industrial|termica de repuesto)\b/,
    urlHint: /(pava|caldera|hervidor)/i,
    storeQueries: ["pava", "caldera"],
    mlQueries: ["pava electrica", "pava", "caldera"],
    fbQueries: ["pava electrica"],
  },
  {
    key: "mixer",
    label: "Mixer o licuadora",
    room: "cocina",
    tier: "B",
    regime: "modelo",
    reason:
      "El chico de mano con procesadora es el que más se usa y el que menos lugar ocupa. Nada deja de poder cocinarse sin él.",
    usedOk: true,
    quantity: 1,
    variants: [
      { key: "mixer", label: "Mixer de mano", match: /\b(mixer|minipimer|de mano)\b/, fallback: true, rank: 1 },
      { key: "licuadora", label: "Licuadora de vaso", match: /\blicuadora\b/, rank: 2 },
    ],
    include: /\b(mixer|minipimer|licuadora|procesadora)\b/,
    exclude: /\b(industrial|de pintura|de cemento|vaso de repuesto|cuchilla de repuesto)\b/,
    urlHint: /(mixer|licuadora|procesadora)/i,
    storeQueries: ["mixer", "licuadora"],
    mlQueries: ["mixer de mano", "licuadora", "procesadora de alimentos"],
    fbQueries: ["licuadora", "mixer"],
  },
  {
    key: "tostadora",
    label: "Tostadora",
    room: "cocina",
    tier: "C",
    regime: "modelo",
    reason: "Una sartén tuesta pan. Es de las últimas compras razonables de una cocina.",
    usedOk: true,
    quantity: 1,
    variants: [{ key: "2rebanadas", label: "2 rebanadas", fallback: true, rank: 1 }],
    include: /\b(tostadora|tostador)\b/,
    exclude: /\b(sandwichera industrial|de repuesto)\b/,
    urlHint: /tostadora/i,
    storeQueries: ["tostadora"],
    mlQueries: ["tostadora"],
    fbQueries: ["tostadora"],
  },
  {
    key: "cafetera",
    label: "Cafetera",
    room: "cocina",
    tier: "C",
    regime: "modelo",
    reason: "Gusto personal, no infraestructura. Entra cuando ya no falta nada.",
    usedOk: true,
    quantity: 1,
    variants: [{ key: "filtro", label: "De filtro", fallback: true, rank: 1 }],
    include: /\b(cafetera|cafeteras)\b/,
    exclude: /\b(capsula de repuesto|italiana de repuesto|filtro de repuesto)\b/,
    urlHint: /cafetera/i,
    storeQueries: ["cafetera"],
    mlQueries: ["cafetera de filtro", "cafetera"],
    fbQueries: ["cafetera"],
  },
  {
    key: "horno-electrico",
    label: "Horno eléctrico",
    room: "cocina",
    tier: "C",
    regime: "modelo",
    reason:
      "Si la cocina ya tiene horno, es redundante. Sólo vale la pena cuando lo que hay es un anafe y el horno se extraña.",
    usedOk: true,
    quantity: 1,
    variants: [{ key: "40l", label: "Hasta 45 L", fallback: true, rank: 1 }],
    include: /\b(horno electrico|horno de mesa|airfryer|freidora de aire)\b/,
    exclude: /\b(a gas|empotrable|industrial|bandeja de repuesto)\b/,
    urlHint: /(horno|airfryer)/i,
    storeQueries: ["horno electrico", "airfryer"],
    mlQueries: ["horno electrico", "freidora de aire"],
    fbQueries: ["horno electrico"],
  },
  // ---------------------------------------------------------------- ropa de cama y baño
  {
    key: "sabanas",
    label: "Juego de sábanas",
    room: "dormitorio",
    tier: "S",
    regime: "commodity",
    reason: "Se duerme la primera noche. Dos juegos para poder lavar uno y usar el otro.",
    usedOk: false,
    quantity: 2,
    variants: [
      { key: "1plaza", label: "1 plaza", match: /\b(1|una) ?plaza\b/, rank: 1 },
      { key: "2plazas", label: "2 plazas o queen", match: /\b(2|dos) ?plazas?\b|\bqueen\b|\bking\b/, fallback: true, rank: 2 },
    ],
    include: /\b(sabana|sabanas|juego de sabanas)\b/,
    exclude: /\b(de cuna|para bebe|ajustable de repuesto|termica de auto)\b/,
    urlHint: /sabana/i,
    storeQueries: ["sabanas", "juego de sabanas"],
    mlQueries: ["juego de sabanas", "sabanas 2 plazas"],
    fbQueries: ["sabanas"],
  },
  {
    key: "almohada",
    label: "Almohada",
    room: "dormitorio",
    tier: "A",
    regime: "commodity",
    reason: "Se puede improvisar la primera noche y no la segunda. Barata y se nota en cómo dormís.",
    usedOk: false,
    quantity: 2,
    variants: [{ key: "estandar", label: "Estándar", fallback: true, rank: 1 }],
    include: /\b(almohada|almohadas)\b/,
    exclude: /\b(de lactancia|para bebe|de viaje|decorativa|cojin|funda)\b/,
    urlHint: /almohada/i,
    storeQueries: ["almohada"],
    mlQueries: ["almohada", "almohada viscoelastica"],
    fbQueries: ["almohada"],
  },
  {
    key: "acolchado",
    label: "Acolchado o frazada",
    room: "dormitorio",
    tier: "A",
    regime: "commodity",
    reason:
      "Depende de la estación en la que te mudes: entre mayo y setiembre es tier S y no admite discusión.",
    usedOk: true,
    quantity: 1,
    variants: [
      { key: "1plaza", label: "1 plaza", match: /\b(1|una) ?plaza\b/, rank: 1 },
      { key: "2plazas", label: "2 plazas o queen", match: /\b(2|dos) ?plazas?\b|\bqueen\b|\bking\b/, fallback: true, rank: 2 },
    ],
    include: /\b(acolchado|frazada|edredon|cubrecama|manta polar)\b/,
    exclude: /\b(de cuna|para bebe|para perro|mascota|de auto)\b/,
    urlHint: /(acolchado|frazada|edredon)/i,
    storeQueries: ["acolchado", "frazada"],
    mlQueries: ["acolchado 2 plazas", "frazada", "edredon"],
    fbQueries: ["acolchado", "frazada"],
  },
  {
    key: "toallas",
    label: "Toallas",
    room: "bano",
    tier: "S",
    regime: "commodity",
    reason: "Bañarse. Dos toallones, por la misma razón que dos juegos de sábanas.",
    usedOk: false,
    quantity: 2,
    variants: [{ key: "toallon", label: "Toallón", fallback: true, rank: 1 }],
    include: /\b(toalla|toallas|toallon|toallones)\b/,
    exclude: /\b(de papel|descartable|de playa|para auto|microfibra de limpieza|femenina)\b/,
    urlHint: /toall/i,
    storeQueries: ["toallas", "toallon"],
    mlQueries: ["toallon", "juego de toallas"],
    fbQueries: ["toallas"],
  },
  {
    key: "cortina-bano",
    label: "Cortina de baño",
    room: "bano",
    tier: "B",
    regime: "commodity",
    reason: "Sólo hace falta si la ducha no tiene mampara. Cuesta poco y evita inundar el baño cada día.",
    usedOk: false,
    quantity: 1,
    variants: [{ key: "estandar", label: "Estándar", fallback: true, rank: 1 }],
    include: /\b(cortina de bano|cortina de ducha)\b/,
    exclude: /\b(barral|riel|ganchos de repuesto)\b/,
    urlHint: /cortina/i,
    storeQueries: ["cortina de bano"],
    mlQueries: ["cortina de bano"],
    fbQueries: ["cortina de bano"],
  },
  // ---------------------------------------------------------------- limpieza y clima
  {
    key: "limpieza",
    label: "Kit de limpieza",
    room: "limpieza",
    tier: "S",
    regime: "commodity",
    reason:
      "Balde, escoba, secador y trapo de piso. Es lo primero que se necesita, porque la casa vacía se recibe sucia y hay que limpiarla antes de meter nada.",
    usedOk: false,
    quantity: 1,
    variants: [{ key: "kit", label: "Balde, escoba y secador", fallback: true, rank: 1 }],
    include: /\b(balde|escoba|secador de piso|mopa|set de limpieza|kit de limpieza|lampazo)\b/,
    exclude: /\b(de obra|industrial|de pelo|de ropa|para auto|de juguete|piscina)\b/,
    urlHint: /(balde|escoba|mopa|lampazo)/i,
    storeQueries: ["balde", "escoba", "mopa"],
    mlQueries: ["set de limpieza hogar", "balde y escoba", "mopa"],
    fbQueries: ["set de limpieza"],
  },
  {
    key: "tacho",
    label: "Tacho de basura",
    room: "limpieza",
    tier: "S",
    regime: "commodity",
    reason: "La basura empieza el primer día. Con tapa, salvo que quieras convivir con el olor.",
    usedOk: false,
    quantity: 1,
    variants: [{ key: "conpedal", label: "Con tapa o pedal", fallback: true, rank: 1 }],
    include: /\b(tacho de basura|cesto de basura|papelera|basurero)\b/,
    exclude: /\b(contenedor industrial|de obra|para auto|de reciclaje municipal)\b/,
    urlHint: /(tacho|cesto|basura)/i,
    storeQueries: ["tacho de basura", "cesto de basura"],
    mlQueries: ["tacho de basura con pedal", "cesto de basura cocina"],
    fbQueries: ["tacho de basura"],
  },
  {
    key: "plancha",
    label: "Plancha",
    room: "limpieza",
    tier: "A",
    regime: "modelo",
    reason:
      "Depende enteramente de en qué trabajás. Si usás camisa es tier S; si no, se posterga sin consecuencias.",
    usedOk: true,
    quantity: 1,
    variants: [{ key: "vapor", label: "A vapor", fallback: true, rank: 1 }],
    include: /\b(plancha a vapor|plancha de ropa|plancha electrica|planchita de ropa)\b/,
    exclude: /\b(de pelo|de cocina|bifera|de asado|industrial|de repuesto)\b/,
    urlHint: /plancha/i,
    storeQueries: ["plancha"],
    mlQueries: ["plancha a vapor", "plancha de ropa"],
    fbQueries: ["plancha a vapor"],
  },
  {
    key: "ventilador",
    label: "Ventilador",
    room: "living",
    tier: "A",
    regime: "modelo",
    reason:
      "Diez veces más barato que un aire acondicionado y resuelve el verano uruguayo casi igual de bien. Si te mudás en diciembre, subilo a tier S.",
    usedOk: true,
    quantity: 1,
    variants: [
      { key: "pie", label: "De pie", match: /\bde pie\b|\bpedestal\b/, fallback: true, rank: 1 },
      { key: "techo", label: "De techo", match: /\bde techo\b/, rank: 2 },
    ],
    include: /\b(ventilador|ventiladores)\b/,
    exclude: /\b(de pc|de notebook|extractor|de auto|de repuesto|cooler)\b/,
    urlHint: /ventilador/i,
    storeQueries: ["ventilador"],
    mlQueries: ["ventilador de pie", "ventilador de techo"],
    fbQueries: ["ventilador"],
  },
  {
    key: "estufa",
    label: "Estufa o calefactor",
    room: "living",
    tier: "A",
    regime: "modelo",
    reason:
      "La contracara del ventilador: si te mudás entre mayo y agosto, es tier S. La eléctrica es barata de comprar y cara de usar, y eso se ve en la factura de UTE.",
    usedOk: true,
    quantity: 1,
    variants: [
      { key: "caloventor", label: "Caloventor", match: /\bcaloventor\b/, fallback: true, rank: 1 },
      { key: "panel", label: "Panel o aceite", match: /\b(panel|aceite|radiador)\b/, rank: 2 },
    ],
    include: /\b(estufa|calefactor|caloventor|panel calefactor|radiador de aceite)\b/,
    exclude: /\b(a lena de obra|industrial|de auto|de repuesto|resistencia)\b/,
    urlHint: /(estufa|calefactor|caloventor)/i,
    storeQueries: ["estufa", "calefactor", "caloventor"],
    mlQueries: ["caloventor", "estufa electrica", "panel calefactor"],
    fbQueries: ["estufa electrica", "caloventor"],
  },
  {
    key: "aspiradora",
    label: "Aspiradora",
    room: "limpieza",
    tier: "B",
    regime: "modelo",
    reason: "La escoba hace el 80 % del trabajo. Se justifica con alfombras o mascotas, no antes.",
    usedOk: true,
    quantity: 1,
    variants: [{ key: "trineo", label: "De trineo o escoba", fallback: true, rank: 1 }],
    include: /\b(aspiradora|aspiradoras)\b/,
    exclude: /\b(de auto|industrial|de taller|bolsa de repuesto|robot de repuesto)\b/,
    urlHint: /aspiradora/i,
    storeQueries: ["aspiradora"],
    mlQueries: ["aspiradora", "aspiradora escoba"],
    fbQueries: ["aspiradora"],
  },
  {
    key: "secarropas",
    label: "Secarropas",
    room: "limpieza",
    tier: "C",
    regime: "modelo",
    reason:
      "Un tender y el sol hacen lo mismo gratis. Se vuelve razonable en invierno, en un apartamento sin balcón, y recién ahí.",
    usedOk: true,
    quantity: 1,
    variants: [{ key: "centrifugo", label: "Centrífugo", fallback: true, rank: 1 }],
    include: /\b(secarropas|secadora de ropa)\b/,
    exclude: /\b(lavarropas|tender|de pelo|de repuesto)\b/,
    urlHint: /(secarropas|secadora)/i,
    storeQueries: ["secarropas"],
    mlQueries: ["secarropas", "secarropas centrifugo"],
    fbQueries: ["secarropas"],
  },
  {
    key: "deshumidificador",
    label: "Deshumidificador",
    room: "living",
    tier: "C",
    regime: "modelo",
    reason:
      "Si ya tenés aire acondicionado, su modo dry hace lo mismo y no gastás dos veces. No son idénticos —el deshumidificador junta el agua en un tanque y el aire sólo seca— pero para humedad normal alcanza. Sólo se justifica en una casa que se moja de verdad.",
    usedOk: true,
    quantity: 1,
    variants: [{ key: "10l", label: "10 L/día", fallback: true, rank: 1 }],
    include: /\b(deshumidificador|deshumectador)\b/,
    exclude: /\b(de auto|silica|quimico|pastilla|de repuesto)\b/,
    urlHint: /deshumi/i,
    storeQueries: ["deshumidificador"],
    mlQueries: ["deshumidificador"],
    fbQueries: ["deshumidificador"],
  },
  {
    key: "impresora",
    label: "Impresora",
    room: "living",
    tier: "C",
    regime: "modelo",
    reason:
      "Tiene un caso de uso real y angosto: el trámite de urgencia un domingo de noche, cuando no hay quiosco abierto. Con hijos en la escuela sube de tier; sin ellos, es de las últimas compras.",
    usedOk: true,
    quantity: 1,
    variants: [{ key: "multifuncion", label: "Multifunción", fallback: true, rank: 1 }],
    include: /\b(impresora|multifuncion)\b/,
    exclude: /\b(3d|cartucho|toner|tinta|cabezal|de repuesto|etiquetas|termica de tickets)\b/,
    urlHint: /impresora/i,
    storeQueries: ["impresora"],
    mlQueries: ["impresora multifuncion", "impresora"],
    fbQueries: ["impresora"],
  },
];

/** Every category, keyed. */
export const EQUIPAR_BY_KEY = new Map(EQUIPAR_CATEGORIES.map((category) => [category.key, category]));

export const TIER_ORDER: Record<string, number> = { S: 0, A: 1, B: 2, C: 3 };

export const TIER_LABEL: Record<string, string> = {
  S: "Sin esto la casa no funciona",
  A: "Primeras semanas",
  B: "Cuando hay resto",
  C: "Puede esperar meses",
};
