// Los ingredientes del planificador: composición nutricional, merma, unidad de
// góndola y cómo se les pone precio.
//
// Composición por 100 g CRUDOS y comestibles (USDA FoodData Central y tablas
// argentinas SARA; redondeada). Los ingredientes se pesan crudos porque eso es
// lo que se compra: el plan dice "150 g de pechuga", no "110 g de pollo cocido".
//
// Precio: si el artículo existe en el SIPC (`GET /precios/articles`, mediana
// nacional del día) se usa ese, con el nombre del artículo y el día de medición
// al lado. Si no existe —y el catálogo del SIPC no tiene leche fluida, ni
// legumbres, ni cebolla, ni zanahoria— se usa un estimado FECHADO que la UI
// marca como tal. Nunca un número liso.
import type { Ingredient } from './types'

const n = (kcal: number, protein: number, carbs: number, fat: number, fiber = 0) => ({
  kcal,
  protein,
  carbs,
  fat,
  fiber,
})

/** Estimado de góndola de Montevideo, relevado a mano en septiembre de 2026. */
const EST = '2026-09'

export const INGREDIENTS: ReadonlyArray<Ingredient> = Object.freeze([
  // ── Carnicería ──────────────────────────────────────────────────────────
  {
    id: 'pechuga_pollo',
    name: 'Pechuga de pollo sin hueso',
    category: 'carniceria',
    kind: 'ave',
    per100: n(120, 22.5, 0, 2.6),
    waste: 0,
    pack: { grams: 100, label: 'por kg' },
    byWeight: true,
    price: {
      sipc: {
        pattern: /^Pollo entero fresco/i,
        factor: 1.9,
        note: 'la pechuga sin hueso no está en el SIPC: se toma 1,9× el kilo de pollo entero',
      },
      estimateUyu: 38,
      asOf: EST,
    },
  },
  {
    id: 'pata_muslo',
    name: 'Pata-muslo de pollo (sin piel)',
    category: 'carniceria',
    kind: 'ave',
    per100: n(121, 19.7, 0, 4.4),
    waste: 0.3,
    pack: { grams: 100, label: 'por kg' },
    byWeight: true,
    price: {
      sipc: {
        pattern: /^Pollo entero fresco/i,
        factor: 1.15,
        note: 'la pata-muslo no está en el SIPC: se toma 1,15× el kilo de pollo entero',
      },
      estimateUyu: 22,
      asOf: EST,
    },
  },
  {
    id: 'carne_picada',
    name: 'Carne picada magra',
    category: 'carniceria',
    kind: 'carne-roja',
    per100: n(137, 21.4, 0, 5),
    waste: 0,
    pack: { grams: 100, label: 'por kg' },
    byWeight: true,
    price: { sipc: { pattern: /^Carne picada vacuna Hasta\s+5 %/i }, estimateUyu: 48, asOf: EST },
  },
  {
    id: 'carne_vacuna',
    name: 'Carne vacuna magra (paleta o nalga sin hueso)',
    category: 'carniceria',
    kind: 'carne-roja',
    per100: n(140, 21, 0, 6),
    waste: 0,
    pack: { grams: 100, label: 'por kg' },
    byWeight: true,
    price: {
      sipc: { pattern: /^(Paleta|Nalga|Aguja) vacuna sin\s+hueso/i },
      estimateUyu: 40,
      asOf: EST,
    },
  },
  {
    id: 'merluza',
    name: 'Bifes de merluza',
    category: 'carniceria',
    kind: 'pescado',
    per100: n(80, 17, 0, 1.2),
    waste: 0,
    pack: { grams: 100, label: 'por kg' },
    byWeight: true,
    price: { sipc: { pattern: /^Pescado fresco - Bifes de merluza/i }, estimateUyu: 45, asOf: EST },
  },
  {
    id: 'atun_lata',
    name: 'Atún al natural en lata (escurrido)',
    category: 'almacen',
    kind: 'pescado',
    per100: n(116, 25.5, 0, 0.8),
    waste: 0,
    pack: { grams: 120, label: 'lata de 170 g' },
    price: { estimateUyu: 115, asOf: EST },
  },
  {
    id: 'jamon_cocido',
    name: 'Jamón cocido',
    category: 'lacteos',
    kind: 'carne-roja',
    per100: n(110, 17, 1, 4),
    waste: 0,
    pack: { grams: 100, label: 'por kg' },
    byWeight: true,
    price: { sipc: { pattern: /^Jamón cocido/i }, estimateUyu: 75, asOf: EST },
  },
  // ── Huevos y lácteos ────────────────────────────────────────────────────
  {
    id: 'huevo',
    name: 'Huevos',
    category: 'lacteos',
    kind: 'huevo',
    per100: n(143, 12.6, 0.7, 9.5),
    waste: 0,
    pack: { grams: 300, label: 'media docena' },
    price: {
      sipc: { pattern: /^Huevos colorados/i, edibleGrams: 300 },
      estimateUyu: 120,
      asOf: EST,
    },
  },
  {
    id: 'leche',
    name: 'Leche entera',
    category: 'lacteos',
    kind: 'lacteo',
    per100: n(61, 3.2, 4.8, 3.3),
    waste: 0,
    pack: { grams: 1000, label: '1 L' },
    price: { estimateUyu: 52, asOf: EST },
  },
  {
    id: 'yogur',
    name: 'Yogur',
    category: 'lacteos',
    kind: 'lacteo',
    per100: n(70, 3.3, 10, 1.8),
    waste: 0,
    pack: { grams: 1000, label: '1 L' },
    price: { sipc: { pattern: /^Yogur/i }, estimateUyu: 98, asOf: EST },
  },
  {
    id: 'queso',
    name: 'Queso dambo o muzzarella',
    category: 'lacteos',
    kind: 'lacteo',
    per100: n(320, 24, 2, 24),
    waste: 0,
    pack: { grams: 100, label: 'por kg' },
    byWeight: true,
    price: { estimateUyu: 56, asOf: EST },
  },
  {
    id: 'queso_rallado',
    name: 'Queso rallado',
    category: 'lacteos',
    kind: 'lacteo',
    per100: n(400, 38, 4, 27),
    waste: 0,
    pack: { grams: 80, label: '80 g' },
    price: { sipc: { pattern: /^Queso rallado/i }, estimateUyu: 114, asOf: EST },
  },
  {
    id: 'manteca',
    name: 'Manteca',
    category: 'lacteos',
    kind: 'lacteo',
    per100: n(717, 0.9, 0.1, 81),
    waste: 0,
    pack: { grams: 200, label: '200 g' },
    price: { sipc: { pattern: /^Manteca/i }, estimateUyu: 110, asOf: EST },
    pantry: true,
  },
  {
    id: 'dulce_de_leche',
    name: 'Dulce de leche',
    category: 'almacen',
    kind: 'lacteo',
    per100: n(315, 6.8, 55, 6.5),
    waste: 0,
    pack: { grams: 1000, label: '1 kg' },
    price: { sipc: { pattern: /^Dulce de leche envasado/i }, estimateUyu: 229, asOf: EST },
    pantry: true,
  },
  // ── Legumbres y almacén ─────────────────────────────────────────────────
  {
    id: 'lentejas',
    name: 'Lentejas secas',
    category: 'almacen',
    kind: 'vegetal',
    per100: n(352, 24.6, 63, 1.1, 10.7),
    waste: 0,
    pack: { grams: 500, label: '500 g' },
    price: { estimateUyu: 95, asOf: EST },
  },
  {
    id: 'garbanzos',
    name: 'Garbanzos secos',
    category: 'almacen',
    kind: 'vegetal',
    per100: n(378, 20.5, 63, 6, 12.2),
    waste: 0,
    pack: { grams: 500, label: '500 g' },
    price: { estimateUyu: 110, asOf: EST },
  },
  {
    id: 'arroz',
    name: 'Arroz blanco',
    category: 'almacen',
    kind: 'vegetal',
    per100: n(360, 7, 79, 0.6, 1.3),
    waste: 0,
    pack: { grams: 1000, label: '1 kg' },
    price: { sipc: { pattern: /^Arroz blanco/i }, estimateUyu: 55, asOf: EST },
  },
  {
    id: 'fideos',
    name: 'Fideos secos',
    category: 'almacen',
    kind: 'vegetal',
    per100: n(371, 13, 74, 1.5, 3.2),
    waste: 0,
    pack: { grams: 500, label: '500 g' },
    price: { sipc: { pattern: /^Fideos secos semolados/i }, estimateUyu: 64, asOf: EST },
  },
  {
    id: 'polenta',
    name: 'Harina de maíz (polenta)',
    category: 'almacen',
    kind: 'vegetal',
    per100: n(362, 8.1, 77, 1.2, 4),
    waste: 0,
    pack: { grams: 450, label: '450 g' },
    price: { sipc: { pattern: /^Harina de maíz/i }, estimateUyu: 42, asOf: EST },
  },
  {
    id: 'avena',
    name: 'Avena arrollada',
    category: 'almacen',
    kind: 'vegetal',
    per100: n(389, 16.9, 66, 6.9, 10.6),
    waste: 0,
    pack: { grams: 500, label: '500 g' },
    price: { estimateUyu: 95, asOf: EST },
  },
  {
    id: 'harina',
    name: 'Harina de trigo 0000',
    category: 'almacen',
    kind: 'vegetal',
    per100: n(364, 10.3, 76, 1, 2.7),
    waste: 0,
    pack: { grams: 1000, label: '1 kg' },
    price: { sipc: { pattern: /^Harina trigo (común )?0000/i }, estimateUyu: 56, asOf: EST },
    pantry: true,
  },
  {
    id: 'pan_rallado',
    name: 'Pan rallado',
    category: 'almacen',
    kind: 'vegetal',
    per100: n(395, 13, 72, 5, 4),
    waste: 0,
    pack: { grams: 500, label: '500 g' },
    price: { estimateUyu: 90, asOf: EST },
    pantry: true,
  },
  {
    id: 'pan_molde',
    name: 'Pan de molde',
    category: 'almacen',
    kind: 'vegetal',
    per100: n(265, 9, 49, 3.5, 3),
    waste: 0,
    pack: { grams: 400, label: 'paquete de 400 g' },
    price: { sipc: { pattern: /^Pan de molde/i }, estimateUyu: 126, asOf: EST },
  },
  {
    id: 'galletitas_agua',
    name: 'Galletitas al agua',
    category: 'almacen',
    kind: 'vegetal',
    per100: n(430, 10, 72, 10, 2),
    waste: 0,
    pack: { grams: 140, label: 'paquete de 140 g' },
    price: { sipc: { pattern: /^Galletitas al agua/i }, estimateUyu: 87, asOf: EST },
  },
  {
    id: 'pulpa_tomate',
    name: 'Pulpa de tomate',
    category: 'almacen',
    kind: 'vegetal',
    per100: n(32, 1.3, 6, 0.3, 1.5),
    waste: 0,
    pack: { grams: 1000, label: 'tetra de 1 kg' },
    price: { sipc: { pattern: /^Pulpa de tomate/i }, estimateUyu: 99, asOf: EST },
  },
  {
    id: 'arvejas_lata',
    name: 'Arvejas en conserva (escurridas)',
    category: 'almacen',
    kind: 'vegetal',
    per100: n(69, 4.4, 11, 0.4, 4.1),
    waste: 0,
    pack: { grams: 200, label: 'lata de 300 g' },
    price: {
      sipc: { pattern: /^Arvejas en conserva/i, edibleGrams: 200 },
      estimateUyu: 40,
      asOf: EST,
    },
  },
  {
    id: 'mani',
    name: 'Maní tostado sin sal',
    category: 'almacen',
    kind: 'vegetal',
    per100: n(567, 25.8, 16.1, 49.2, 8.5),
    waste: 0,
    pack: { grams: 250, label: '250 g' },
    price: { estimateUyu: 120, asOf: EST },
  },
  {
    id: 'cocoa',
    name: 'Cocoa',
    category: 'almacen',
    kind: 'vegetal',
    per100: n(380, 6, 80, 3.5),
    waste: 0,
    pack: { grams: 500, label: '500 g' },
    price: { sipc: { pattern: /^Cocoa/i }, estimateUyu: 316, asOf: EST },
    pantry: true,
  },
  {
    id: 'azucar',
    name: 'Azúcar',
    category: 'almacen',
    kind: 'vegetal',
    per100: n(387, 0, 100, 0),
    waste: 0,
    pack: { grams: 1000, label: '1 kg' },
    price: { sipc: { pattern: /^Azúcar blanco/i }, estimateUyu: 48, asOf: EST },
    pantry: true,
  },
  // ── Verdulería ──────────────────────────────────────────────────────────
  {
    id: 'papa',
    name: 'Papa',
    category: 'verduleria',
    kind: 'vegetal',
    per100: n(77, 2, 17, 0.1, 2.2),
    waste: 0.15,
    pack: { grams: 100, label: 'por kg' },
    byWeight: true,
    price: { sipc: { pattern: /^Papa (Blanca|Rosada)/i }, estimateUyu: 8, asOf: EST },
  },
  {
    id: 'boniato',
    name: 'Boniato',
    category: 'verduleria',
    kind: 'vegetal',
    per100: n(86, 1.6, 20, 0.1, 3),
    waste: 0.15,
    pack: { grams: 100, label: 'por kg' },
    byWeight: true,
    price: { estimateUyu: 7.5, asOf: EST },
  },
  {
    id: 'zapallo',
    name: 'Zapallo (calabacín o criollo)',
    category: 'verduleria',
    kind: 'vegetal',
    per100: n(34, 1.1, 8, 0.1, 1.5),
    waste: 0.25,
    pack: { grams: 100, label: 'por kg' },
    byWeight: true,
    price: { sipc: { pattern: /^Zapallo/i }, estimateUyu: 6.5, asOf: EST },
  },
  {
    id: 'cebolla',
    name: 'Cebolla',
    category: 'verduleria',
    kind: 'vegetal',
    per100: n(40, 1.1, 9.3, 0.1, 1.7),
    waste: 0.1,
    pack: { grams: 100, label: 'por kg' },
    byWeight: true,
    price: { sipc: { pattern: /^Cebolla/i }, estimateUyu: 6, asOf: EST },
  },
  {
    id: 'zanahoria',
    name: 'Zanahoria',
    category: 'verduleria',
    kind: 'vegetal',
    per100: n(41, 0.9, 9.6, 0.2, 2.8),
    waste: 0.1,
    pack: { grams: 100, label: 'por kg' },
    byWeight: true,
    price: { estimateUyu: 5.5, asOf: EST },
  },
  {
    id: 'tomate',
    name: 'Tomate',
    category: 'verduleria',
    kind: 'vegetal',
    per100: n(18, 0.9, 3.9, 0.2, 1.2),
    waste: 0,
    pack: { grams: 100, label: 'por kg' },
    byWeight: true,
    price: { sipc: { pattern: /^Tomate/i }, estimateUyu: 25, asOf: EST },
  },
  {
    id: 'morron',
    name: 'Morrón',
    category: 'verduleria',
    kind: 'vegetal',
    per100: n(26, 1, 6, 0.3, 2.1),
    waste: 0.2,
    pack: { grams: 100, label: 'por kg' },
    byWeight: true,
    price: { estimateUyu: 19, asOf: EST },
  },
  {
    id: 'brocoli',
    name: 'Brócoli',
    category: 'verduleria',
    kind: 'vegetal',
    per100: n(34, 2.8, 6.6, 0.4, 2.6),
    waste: 0.3,
    pack: { grams: 100, label: 'por kg' },
    byWeight: true,
    price: { estimateUyu: 16, asOf: EST },
  },
  {
    id: 'acelga',
    name: 'Acelga',
    category: 'verduleria',
    kind: 'vegetal',
    per100: n(19, 1.8, 3.7, 0.2, 1.6),
    waste: 0.2,
    pack: { grams: 400, label: 'atado' },
    price: { estimateUyu: 70, asOf: EST },
  },
  {
    id: 'lechuga',
    name: 'Lechuga',
    category: 'verduleria',
    kind: 'vegetal',
    per100: n(15, 1.4, 2.9, 0.2, 1.3),
    waste: 0.15,
    pack: { grams: 300, label: 'planta' },
    price: { sipc: { pattern: /^Lechuga/i, edibleGrams: 300 }, estimateUyu: 55, asOf: EST },
  },
  {
    id: 'ajo',
    name: 'Ajo',
    category: 'verduleria',
    kind: 'vegetal',
    per100: n(149, 6.4, 33, 0.5, 2.1),
    waste: 0.1,
    pack: { grams: 50, label: 'cabeza' },
    price: { estimateUyu: 30, asOf: EST },
    pantry: true,
  },
  {
    id: 'limon',
    name: 'Limón',
    category: 'verduleria',
    kind: 'vegetal',
    per100: n(29, 1.1, 9.3, 0.3, 2.8),
    waste: 0.4,
    pack: { grams: 100, label: 'por kg' },
    byWeight: true,
    price: { estimateUyu: 9, asOf: EST },
  },
  {
    id: 'banana',
    name: 'Banana',
    category: 'verduleria',
    kind: 'vegetal',
    per100: n(89, 1.1, 22.8, 0.3, 2.6),
    waste: 0.35,
    pack: { grams: 100, label: 'por kg' },
    byWeight: true,
    price: { sipc: { pattern: /^Banana/i }, estimateUyu: 10, asOf: EST },
  },
  {
    id: 'manzana',
    name: 'Manzana',
    category: 'verduleria',
    kind: 'vegetal',
    per100: n(52, 0.3, 13.8, 0.2, 2.4),
    waste: 0.1,
    pack: { grams: 100, label: 'por kg' },
    byWeight: true,
    price: { sipc: { pattern: /^Manzana/i }, estimateUyu: 13, asOf: EST },
  },
  {
    id: 'naranja',
    name: 'Naranja',
    category: 'verduleria',
    kind: 'vegetal',
    per100: n(47, 0.9, 11.8, 0.1, 2.4),
    waste: 0.27,
    pack: { grams: 100, label: 'por kg' },
    byWeight: true,
    price: { sipc: { pattern: /^Naranja/i }, estimateUyu: 6, asOf: EST },
  },
  // ── Despensa ────────────────────────────────────────────────────────────
  {
    id: 'aceite',
    name: 'Aceite de girasol',
    category: 'despensa',
    kind: 'vegetal',
    per100: n(884, 0, 0, 100),
    waste: 0,
    pack: { grams: 900, label: '900 ml' },
    price: { sipc: { pattern: /^Aceite de girasol - /i }, estimateUyu: 105, asOf: EST },
    pantry: true,
  },
  {
    id: 'sal',
    name: 'Sal fina',
    category: 'despensa',
    kind: 'vegetal',
    per100: n(0, 0, 0, 0),
    waste: 0,
    pack: { grams: 500, label: '500 g' },
    price: { sipc: { pattern: /^Sal fina/i }, estimateUyu: 57, asOf: EST },
    pantry: true,
  },
  {
    id: 'especias',
    name: 'Especias (pimentón, orégano, comino, pimienta)',
    category: 'despensa',
    kind: 'vegetal',
    per100: n(0, 0, 0, 0),
    waste: 0,
    pack: { grams: 50, label: 'frasco de 50 g' },
    price: { estimateUyu: 70, asOf: EST },
    pantry: true,
  },
])

export const INGREDIENT_BY_ID: ReadonlyMap<string, Ingredient> = new Map(
  INGREDIENTS.map(ingredient => [ingredient.id, ingredient])
)

export function ingredientById(id: string): Ingredient {
  const ingredient = INGREDIENT_BY_ID.get(id)
  if (!ingredient) throw new Error(`Ingrediente desconocido: ${id}`)
  return ingredient
}
