// Las recetas del planificador. Todas de despensa uruguaya, todas fáciles, y
// cada una dice cuántos días aguanta en la heladera, si se puede freezar y cómo
// se recalienta: eso es lo que el planificador usa como restricción, no como
// adorno (ver `safety.ts`).
//
// Gramos POR PORCIÓN base, crudos. La porción se escala después según las kcal
// de la persona (`planner.ts`), igual para todos los tuppers del mismo plato.
//
// Días de heladera: comidas cocidas 3 (USDA dice 3–4; se toma 3), arroz cocido
// 2 (Bacillus cereus sobrevive la cocción y crece a temperatura ambiente),
// pescado cocido 2, con huevo o ensalada sin aderezar 3. Freezer: hasta 60 días
// de calidad, descongelar en la heladera la noche anterior.
import type { Recipe } from './types'

const MICRO_3 = 'Microondas 3 min a potencia máxima, revolver a la mitad, hasta que humee'
const MICRO_2 = 'Microondas 2 min a potencia máxima, hasta que humee'
const MICRO_4 = 'Microondas 4 min a potencia máxima, revolver a la mitad, hasta que humee'

export const RECIPES: ReadonlyArray<Recipe> = Object.freeze([
  // ═══════════════════════ PRINCIPALES (almuerzo / cena) ═══════════════════
  {
    id: 'guiso_lentejas',
    name: 'Guiso de lentejas con papa y verduras',
    slot: 'principal',
    appliances: ['anafe'],
    protein: 'legumbre',
    quick: false,
    batch: true,
    ingredients: [
      { id: 'lentejas', grams: 90 },
      { id: 'papa', grams: 100 },
      { id: 'cebolla', grams: 50 },
      { id: 'zanahoria', grams: 60 },
      { id: 'zapallo', grams: 80 },
      { id: 'pulpa_tomate', grams: 100 },
      { id: 'aceite', grams: 8 },
      { id: 'ajo', grams: 4 },
      { id: 'especias', grams: 2 },
      { id: 'sal', grams: 1 },
    ],
    steps: [
      'Lavar las lentejas (no hace falta remojo). Picar cebolla, ajo, zanahoria, papa y zapallo en cubos chicos.',
      'En la olla, rehogar cebolla y ajo con el aceite 3 min. Sumar zanahoria, pimentón y comino, 2 min más.',
      'Agregar lentejas, pulpa de tomate y agua hasta cubrir 3 dedos por encima. Hervir y bajar a fuego suave 25 min, tapado.',
      'Sumar papa y zapallo y cocinar 20 min más, revolviendo. Si queda seco, un poco de agua caliente. Salar al final.',
      'Enfriar destapado 30 min, repartir en tuppers y a la heladera o al freezer.',
    ],
    prepMinutes: 15,
    cookMinutes: 50,
    storage: { fridgeDays: 3, freezable: true, reheat: MICRO_4 },
    why: 'Proteína vegetal barata, fibra alta y el plato que mejor se freeza de todos.',
  },
  {
    id: 'arroz_con_pollo',
    name: 'Arroz con pollo y verduras (una olla)',
    slot: 'principal',
    appliances: ['anafe'],
    protein: 'pollo',
    quick: false,
    batch: true,
    ingredients: [
      { id: 'pechuga_pollo', grams: 130 },
      { id: 'arroz', grams: 70 },
      { id: 'cebolla', grams: 40 },
      { id: 'morron', grams: 40 },
      { id: 'zanahoria', grams: 40 },
      { id: 'arvejas_lata', grams: 50 },
      { id: 'pulpa_tomate', grams: 60 },
      { id: 'aceite', grams: 6 },
      { id: 'ajo', grams: 3 },
      { id: 'especias', grams: 2 },
      { id: 'sal', grams: 1 },
    ],
    steps: [
      'Cortar la pechuga en cubos de 2 cm; picar cebolla, morrón, zanahoria y ajo.',
      'Dorar el pollo con el aceite 4 min a fuego fuerte. Retirar y reservar.',
      'En la misma olla, rehogar las verduras 5 min. Sumar pimentón, el arroz y revolver 1 min.',
      'Agregar pulpa de tomate y 2 tazas de agua caliente por taza de arroz. Volver a poner el pollo, tapar y cocinar 18 min a fuego mínimo.',
      'Sumar las arvejas, apagar y dejar reposar 5 min tapado. Enfriar y repartir en tuppers.',
    ],
    prepMinutes: 15,
    cookMinutes: 35,
    storage: { fridgeDays: 2, freezable: true, reheat: MICRO_3 },
    why: 'Todo en una olla, sin vigilar, y rinde igual del freezer.',
  },
  {
    id: 'milanesas_pollo',
    name: 'Milanesas de pollo al airfryer con puré de zapallo',
    slot: 'principal',
    appliances: ['airfryer', 'microondas'],
    alternatives: { airfryer: 'horno' },
    protein: 'pollo',
    quick: false,
    batch: true,
    ingredients: [
      { id: 'pechuga_pollo', grams: 150 },
      { id: 'huevo', grams: 25 },
      { id: 'pan_rallado', grams: 30 },
      { id: 'zapallo', grams: 250 },
      { id: 'manteca', grams: 5 },
      { id: 'aceite', grams: 3 },
      { id: 'especias', grams: 1 },
      { id: 'sal', grams: 1 },
    ],
    steps: [
      'Cortar la pechuga en filetes de 1 cm, salar. Pasar por huevo batido con ajo y orégano y después por pan rallado.',
      'Airfryer a 200 °C, 12 min, dando vuelta a la mitad y pintando con un poco de aceite. En horno: 200 °C, 25 min. Hacer en tandas sin encimar.',
      'Zapallo en cubos, en un bol tapado con 2 cucharadas de agua: microondas 8 min a máxima potencia. Pisar con la manteca y sal.',
      'Enfriar milanesas y puré por separado y armar los tuppers.',
    ],
    prepMinutes: 20,
    cookMinutes: 30,
    storage: {
      fridgeDays: 3,
      freezable: true,
      reheat: 'Microondas 2 min; si querés la milanesa crocante, 3 min más en el airfryer a 180 °C',
    },
    why: 'La milanesa es el plato uruguayo por excelencia, y en airfryer lleva una cucharada de aceite.',
  },
  {
    id: 'bolonesa_fideos',
    name: 'Fideos con boloñesa',
    slot: 'principal',
    appliances: ['anafe'],
    protein: 'carne',
    quick: false,
    batch: true,
    ingredients: [
      { id: 'carne_picada', grams: 100 },
      { id: 'fideos', grams: 90 },
      { id: 'pulpa_tomate', grams: 120 },
      { id: 'cebolla', grams: 40 },
      { id: 'zanahoria', grams: 30 },
      { id: 'aceite', grams: 5 },
      { id: 'ajo', grams: 3 },
      { id: 'queso_rallado', grams: 8 },
      { id: 'especias', grams: 2 },
      { id: 'sal', grams: 1 },
    ],
    steps: [
      'Picar cebolla, zanahoria y ajo bien chicos. Rehogar con el aceite 5 min.',
      'Sumar la carne picada y dorar 5 min desarmando los grumos. Salar, orégano y pimienta.',
      'Agregar la pulpa de tomate y cocinar a fuego suave 20 min, tapado.',
      'Hervir los fideos 1 min MENOS de lo que dice el paquete (terminan de cocinarse al recalentar). Colar y mezclar con la salsa.',
      'Enfriar, repartir en tuppers y espolvorear el queso rallado al servir.',
    ],
    prepMinutes: 10,
    cookMinutes: 35,
    storage: { fridgeDays: 3, freezable: true, reheat: MICRO_3 },
    why: 'La salsa se freeza perfecta y la pasta al dente aguanta el microondas.',
  },
  {
    id: 'pollo_papa_zapallo',
    name: 'Pata-muslo con papa y zapallo al airfryer',
    slot: 'principal',
    appliances: ['airfryer'],
    alternatives: { airfryer: 'horno' },
    protein: 'pollo',
    quick: false,
    batch: true,
    ingredients: [
      { id: 'pata_muslo', grams: 180 },
      { id: 'papa', grams: 200 },
      { id: 'zapallo', grams: 150 },
      { id: 'aceite', grams: 6 },
      { id: 'ajo', grams: 3 },
      { id: 'especias', grams: 2 },
      { id: 'sal', grams: 1 },
    ],
    steps: [
      'Sacar la piel de la pata-muslo (o dejarla y sacarla al servir). Salar, pimentón, ajo picado.',
      'Papa y zapallo en cubos de 3 cm con la mitad del aceite y sal.',
      'Airfryer a 190 °C: primero el pollo 25 min dando vuelta a la mitad; después las verduras 18 min, sacudiendo a la mitad. En horno: todo junto en una placa, 200 °C, 40 min.',
      'Enfriar y repartir: pollo y verduras en el mismo tupper.',
    ],
    prepMinutes: 15,
    cookMinutes: 45,
    storage: { fridgeDays: 3, freezable: true, reheat: MICRO_3 },
    why: 'El corte más barato del pollo y cero atención mientras se cocina.',
  },
  {
    id: 'albondigas_arroz',
    name: 'Albóndigas en salsa con arroz',
    slot: 'principal',
    appliances: ['anafe', 'airfryer'],
    alternatives: { airfryer: 'anafe' },
    protein: 'carne',
    quick: false,
    batch: true,
    ingredients: [
      { id: 'carne_picada', grams: 120 },
      { id: 'huevo', grams: 15 },
      { id: 'pan_rallado', grams: 15 },
      { id: 'cebolla', grams: 30 },
      { id: 'pulpa_tomate', grams: 120 },
      { id: 'arroz', grams: 70 },
      { id: 'aceite', grams: 5 },
      { id: 'ajo', grams: 3 },
      { id: 'especias', grams: 2 },
      { id: 'sal', grams: 1 },
    ],
    steps: [
      'Mezclar carne, huevo, pan rallado, la mitad de la cebolla picada, ajo, sal y comino. Formar bolitas del tamaño de una nuez.',
      'Airfryer a 190 °C, 10 min (o dorarlas en sartén con el aceite).',
      'Rehogar el resto de la cebolla, sumar la pulpa de tomate y las albóndigas; 15 min a fuego suave.',
      'Arroz: 1 medida de arroz por 2 de agua, tapado, 15 min a fuego mínimo desde que hierve.',
      'Enfriar y armar los tuppers con arroz abajo y albóndigas con salsa arriba.',
    ],
    prepMinutes: 20,
    cookMinutes: 35,
    storage: { fridgeDays: 2, freezable: true, reheat: MICRO_3 },
    why: 'Las albóndigas en salsa son de lo que mejor sale del freezer.',
  },
  {
    id: 'merluza_pure',
    name: 'Merluza al airfryer con puré de papa y zanahoria',
    slot: 'principal',
    appliances: ['airfryer', 'anafe'],
    alternatives: { airfryer: 'horno' },
    protein: 'pescado',
    quick: false,
    batch: true,
    ingredients: [
      { id: 'merluza', grams: 180 },
      { id: 'papa', grams: 200 },
      { id: 'zanahoria', grams: 80 },
      { id: 'leche', grams: 30 },
      { id: 'manteca', grams: 5 },
      { id: 'limon', grams: 20 },
      { id: 'aceite', grams: 3 },
      { id: 'especias', grams: 1 },
      { id: 'sal', grams: 1 },
    ],
    steps: [
      'Secar los bifes con papel, salar, pimienta, jugo de limón y un hilo de aceite.',
      'Airfryer a 190 °C, 9 min, sin dar vuelta. En horno: 200 °C, 15 min.',
      'Hervir papa y zanahoria en cubos 20 min. Pisar con leche, manteca y sal.',
      'Enfriar y armar los tuppers. El pescado va aparte del puré si tenés tuppers con división.',
    ],
    prepMinutes: 15,
    cookMinutes: 30,
    storage: { fridgeDays: 2, freezable: true, reheat: MICRO_2 },
    why: 'Pescado una vez por semana; la merluza es la única que mide el SIPC.',
  },
  {
    id: 'polenta_carne_queso',
    name: 'Polenta con salsa de carne y queso',
    slot: 'principal',
    appliances: ['anafe'],
    protein: 'carne',
    quick: false,
    batch: true,
    ingredients: [
      { id: 'polenta', grams: 70 },
      { id: 'carne_picada', grams: 80 },
      { id: 'pulpa_tomate', grams: 120 },
      { id: 'cebolla', grams: 30 },
      { id: 'queso', grams: 30 },
      { id: 'leche', grams: 50 },
      { id: 'aceite', grams: 5 },
      { id: 'especias', grams: 2 },
      { id: 'sal', grams: 1 },
    ],
    steps: [
      'Rehogar la cebolla con el aceite, dorar la carne 5 min, sumar la pulpa de tomate y cocinar 15 min a fuego suave.',
      'Polenta: por cada medida de polenta, 3 de agua hirviendo con sal y la leche. Volcar en lluvia revolviendo, 5 min (o lo que diga el paquete).',
      'Repartir la polenta en los tuppers, la salsa arriba y el queso en cubos encima.',
      'Enfriar destapado antes de tapar.',
    ],
    prepMinutes: 10,
    cookMinutes: 25,
    storage: { fridgeDays: 3, freezable: true, reheat: MICRO_3 },
    why: 'La polenta se corta firme en el tupper y vuelve cremosa en el microondas.',
  },
  {
    id: 'ensalada_garbanzos',
    name: 'Ensalada de garbanzos con huevo y verduras',
    slot: 'principal',
    appliances: ['anafe'],
    protein: 'legumbre',
    quick: false,
    batch: true,
    ingredients: [
      { id: 'garbanzos', grams: 70 },
      { id: 'huevo', grams: 50 },
      { id: 'tomate', grams: 80 },
      { id: 'morron', grams: 40 },
      { id: 'cebolla', grams: 30 },
      { id: 'lechuga', grams: 40 },
      { id: 'aceite', grams: 8 },
      { id: 'limon', grams: 15 },
      { id: 'especias', grams: 1 },
      { id: 'sal', grams: 1 },
    ],
    steps: [
      'Remojar los garbanzos la noche anterior (12 h). Hervir 60 min hasta que estén tiernos (o 25 min en olla a presión). Colar y enfriar.',
      'Huevos duros: 10 min desde que hierve el agua, enfriar en agua fría y pelar.',
      'Tomate, morrón y cebolla en cubos chicos. Mezclar con los garbanzos, comino, sal y el aceite.',
      'Armar los tuppers con la lechuga aparte y el limón para el momento de comer: aderezada se marchita en un día.',
    ],
    prepMinutes: 15,
    cookMinutes: 60,
    storage: {
      fridgeDays: 3,
      freezable: false,
      cold: true,
      reheat: 'Se come fría. Sacar de la heladera 15 min antes y sumar lechuga y limón al momento',
    },
    why: 'Un principal que no se recalienta: útil el día que no hay microondas.',
  },
  {
    id: 'pastel_carne',
    name: 'Pastel de carne con puré de papa y zapallo',
    slot: 'principal',
    appliances: ['anafe', 'microondas'],
    protein: 'carne',
    quick: false,
    batch: true,
    ingredients: [
      { id: 'carne_picada', grams: 110 },
      { id: 'cebolla', grams: 40 },
      { id: 'papa', grams: 150 },
      { id: 'zapallo', grams: 100 },
      { id: 'huevo', grams: 25 },
      { id: 'leche', grams: 30 },
      { id: 'arvejas_lata', grams: 40 },
      { id: 'aceite', grams: 5 },
      { id: 'especias', grams: 2 },
      { id: 'sal', grams: 1 },
    ],
    steps: [
      'Papa y zapallo en cubos, en bol tapado con 3 cucharadas de agua: microondas 10 min. Pisar con la leche y sal.',
      'Rehogar la cebolla con el aceite, dorar la carne 6 min, salar, pimentón. Apagar y mezclar con las arvejas y el huevo batido.',
      'En cada tupper: capa de carne abajo, puré arriba. Si tenés horno o airfryer, 10 min a 200 °C para gratinar; si no, va así.',
      'Enfriar destapado antes de tapar.',
    ],
    prepMinutes: 15,
    cookMinutes: 25,
    storage: { fridgeDays: 3, freezable: true, reheat: MICRO_4 },
    why: 'Se arma directo en el tupper y se freeza entero.',
  },
  {
    id: 'bunuelos_acelga',
    name: 'Buñuelos de acelga al airfryer con arroz y huevo duro',
    slot: 'principal',
    appliances: ['airfryer', 'anafe'],
    alternatives: { airfryer: 'horno' },
    protein: 'huevo',
    quick: false,
    batch: true,
    ingredients: [
      { id: 'acelga', grams: 120 },
      { id: 'huevo', grams: 110 },
      { id: 'harina', grams: 30 },
      { id: 'cebolla', grams: 30 },
      { id: 'queso_rallado', grams: 10 },
      { id: 'arroz', grams: 70 },
      { id: 'aceite', grams: 5 },
      { id: 'especias', grams: 1 },
      { id: 'sal', grams: 1 },
    ],
    steps: [
      'Lavar y picar la acelga cruda (hojas y pencas finas). Mezclar con la cebolla picada, 1 huevo batido por porción, harina, queso rallado, sal y pimienta hasta tener una masa espesa.',
      'Poner cucharadas sobre papel manteca en el airfryer, pintar con aceite: 180 °C, 12 min, dando vuelta a la mitad. En horno: 200 °C, 20 min.',
      'Arroz: 1 medida por 2 de agua, 15 min tapado. Huevos duros: 10 min desde el hervor.',
      'Enfriar y armar los tuppers con arroz, 3–4 buñuelos y un huevo duro pelado.',
    ],
    prepMinutes: 20,
    cookMinutes: 30,
    storage: { fridgeDays: 2, freezable: true, reheat: MICRO_3 },
    why: 'Verdura de hoja que los chicos comen, y sin fritura.',
  },
  {
    id: 'tortilla_papa',
    name: 'Tortilla de papa y cebolla con ensalada',
    slot: 'principal',
    appliances: ['microondas', 'anafe'],
    protein: 'huevo',
    quick: false,
    batch: true,
    ingredients: [
      { id: 'huevo', grams: 120 },
      { id: 'papa', grams: 180 },
      { id: 'cebolla', grams: 50 },
      { id: 'aceite', grams: 6 },
      { id: 'tomate', grams: 100 },
      { id: 'lechuga', grams: 40 },
      { id: 'sal', grams: 1 },
    ],
    steps: [
      'Papa en cubos chicos y cebolla en juliana, en bol tapado con 2 cucharadas de agua: microondas 8 min.',
      'Batir los huevos con sal, mezclar con la papa y cebolla escurridas.',
      'En sartén antiadherente con el aceite, a fuego medio-bajo, 6 min por lado (dar vuelta con un plato). Cortar en porciones cuando enfríe.',
      'La ensalada de tomate y lechuga va en un tupper aparte, sin aderezar.',
    ],
    prepMinutes: 15,
    cookMinutes: 25,
    storage: {
      fridgeDays: 3,
      freezable: false,
      reheat: 'Microondas 1 min y medio; también se come fría',
    },
    why: 'No se freeza (la papa cocida cambia de textura) y por eso va en los primeros días.',
  },
  {
    id: 'arroz_salteado_huevo',
    name: 'Arroz salteado con huevo, brócoli y zanahoria',
    slot: 'principal',
    appliances: ['anafe'],
    protein: 'huevo',
    quick: false,
    batch: true,
    ingredients: [
      { id: 'arroz', grams: 80 },
      { id: 'huevo', grams: 100 },
      { id: 'brocoli', grams: 120 },
      { id: 'zanahoria', grams: 60 },
      { id: 'cebolla', grams: 40 },
      { id: 'ajo', grams: 3 },
      { id: 'aceite', grams: 8 },
      { id: 'especias', grams: 1 },
      { id: 'sal', grams: 1 },
    ],
    steps: [
      'Arroz: 1 medida por 2 de agua, 15 min tapado. Dejar enfriar (el arroz frío saltea mejor).',
      'Brócoli en arbolitos chicos y zanahoria en bastones finos: 3 min en agua hirviendo, colar.',
      'En sartén grande con la mitad del aceite, revolver los huevos 1 min y reservar.',
      'Con el resto del aceite, saltear cebolla y ajo 2 min, sumar verduras y arroz a fuego fuerte 4 min, volver los huevos, sal y pimienta.',
    ],
    prepMinutes: 15,
    cookMinutes: 30,
    storage: { fridgeDays: 2, freezable: true, reheat: MICRO_3 },
    why: 'El plato de "quedó arroz" convertido en principal con proteína.',
  },
  {
    id: 'pollo_desmenuzado_boniato',
    name: 'Pollo desmenuzado en salsa con boniato al airfryer',
    slot: 'principal',
    appliances: ['anafe', 'airfryer'],
    alternatives: { airfryer: 'horno' },
    protein: 'pollo',
    quick: false,
    batch: true,
    ingredients: [
      { id: 'pechuga_pollo', grams: 150 },
      { id: 'pulpa_tomate', grams: 100 },
      { id: 'cebolla', grams: 40 },
      { id: 'morron', grams: 40 },
      { id: 'boniato', grams: 220 },
      { id: 'aceite', grams: 6 },
      { id: 'ajo', grams: 3 },
      { id: 'especias', grams: 2 },
      { id: 'sal', grams: 1 },
    ],
    steps: [
      'Hervir la pechuga entera en agua con sal 18 min. Enfriar un poco y desmenuzar con dos tenedores.',
      'Rehogar cebolla, morrón y ajo con la mitad del aceite, sumar pulpa de tomate, pimentón y comino, y el pollo desmenuzado; 10 min a fuego suave.',
      'Boniato en gajos con el resto del aceite y sal: airfryer 190 °C, 18 min, sacudiendo a la mitad. En horno: 200 °C, 30 min.',
      'Enfriar y armar los tuppers.',
    ],
    prepMinutes: 15,
    cookMinutes: 40,
    storage: { fridgeDays: 3, freezable: true, reheat: MICRO_3 },
    why: 'Pollo desmenuzado en salsa es lo que mejor sobrevive al freezer y al microondas.',
  },
  {
    id: 'guiso_carne_papa',
    name: 'Guiso de carne con papa, zanahoria y arvejas',
    slot: 'principal',
    appliances: ['anafe'],
    protein: 'carne',
    quick: false,
    batch: true,
    ingredients: [
      { id: 'carne_vacuna', grams: 130 },
      { id: 'papa', grams: 150 },
      { id: 'zanahoria', grams: 60 },
      { id: 'cebolla', grams: 40 },
      { id: 'arvejas_lata', grams: 50 },
      { id: 'pulpa_tomate', grams: 100 },
      { id: 'aceite', grams: 6 },
      { id: 'ajo', grams: 3 },
      { id: 'especias', grams: 2 },
      { id: 'sal', grams: 1 },
    ],
    steps: [
      'Carne en cubos de 3 cm. Dorar con el aceite a fuego fuerte 5 min. Retirar.',
      'Rehogar cebolla y ajo 3 min, sumar zanahoria, pimentón, la carne y la pulpa de tomate con 1 taza de agua. Tapar y cocinar 40 min a fuego mínimo.',
      'Sumar la papa en cubos y 15 min más. Al final, las arvejas y sal.',
      'Enfriar destapado 30 min y repartir.',
    ],
    prepMinutes: 15,
    cookMinutes: 60,
    storage: { fridgeDays: 3, freezable: true, reheat: MICRO_4 },
    why: 'El guiso de domingo, que es justo el día de cocina.',
  },
  {
    id: 'fideos_atun',
    name: 'Fideos con atún, tomate y arvejas',
    slot: 'principal',
    appliances: ['anafe'],
    protein: 'pescado',
    quick: true,
    batch: true,
    ingredients: [
      { id: 'fideos', grams: 90 },
      { id: 'atun_lata', grams: 60 },
      { id: 'pulpa_tomate', grams: 100 },
      { id: 'cebolla', grams: 30 },
      { id: 'arvejas_lata', grams: 50 },
      { id: 'aceite', grams: 6 },
      { id: 'ajo', grams: 3 },
      { id: 'especias', grams: 1 },
      { id: 'sal', grams: 1 },
    ],
    steps: [
      'Poner el agua a hervir para los fideos.',
      'Rehogar cebolla y ajo con el aceite 3 min, sumar la pulpa de tomate, orégano y 8 min a fuego suave. Apagar y sumar el atún escurrido y las arvejas.',
      'Hervir los fideos 1 min menos que el paquete, colar y mezclar con la salsa.',
      'Si es para guardar: enfriar y repartir en tuppers.',
    ],
    prepMinutes: 5,
    cookMinutes: 15,
    storage: { fridgeDays: 3, freezable: true, reheat: MICRO_3 },
    why: 'Veinte minutos y todo de lata: sirve para el día que no hubo cocina.',
  },
  {
    id: 'omelette_queso',
    name: 'Omelette de queso y tomate con pan',
    slot: 'principal',
    appliances: ['anafe'],
    protein: 'huevo',
    quick: true,
    batch: false,
    ingredients: [
      { id: 'huevo', grams: 150 },
      { id: 'queso', grams: 30 },
      { id: 'tomate', grams: 80 },
      { id: 'pan_molde', grams: 50 },
      { id: 'aceite', grams: 4 },
      { id: 'sal', grams: 1 },
    ],
    steps: [
      'Batir 3 huevos con sal. Tomate en cubos.',
      'Sartén antiadherente con el aceite a fuego medio: volcar los huevos, cuando cuajan los bordes poner queso y tomate y doblar.',
      '1 min más, servir con el pan tostado.',
    ],
    prepMinutes: 3,
    cookMinutes: 7,
    storage: { fridgeDays: 0, freezable: false, reheat: 'Se hace y se come en el momento' },
    why: 'El comodín de 10 minutos para el día que el plan no llega.',
  },
  {
    id: 'sandwich_atun',
    name: 'Sándwich de atún, lechuga y tomate con fruta',
    slot: 'principal',
    appliances: ['sin-coccion'],
    protein: 'pescado',
    quick: true,
    batch: false,
    ingredients: [
      { id: 'atun_lata', grams: 80 },
      { id: 'pan_molde', grams: 70 },
      { id: 'lechuga', grams: 30 },
      { id: 'tomate', grams: 60 },
      { id: 'aceite', grams: 5 },
      { id: 'limon', grams: 10 },
      { id: 'manzana', grams: 150 },
    ],
    steps: [
      'Escurrir el atún y mezclar con el aceite, limón y pimienta.',
      'Armar el sándwich con lechuga y tomate en rodajas. Fruta de postre.',
    ],
    prepMinutes: 5,
    cookMinutes: 0,
    storage: { fridgeDays: 0, freezable: false, reheat: 'Se arma y se come en el momento' },
    why: 'Sin cocina: para el día 7 si no hay freezer.',
  },

  // ═══════════════════════════════ DESAYUNOS ════════════════════════════════
  {
    id: 'avena_microondas',
    name: 'Avena con leche, banana y maní (microondas)',
    slot: 'desayuno',
    appliances: ['microondas'],
    alternatives: { microondas: 'anafe' },
    protein: 'lacteo',
    quick: true,
    batch: false,
    ingredients: [
      { id: 'avena', grams: 50 },
      { id: 'leche', grams: 200 },
      { id: 'banana', grams: 100 },
      { id: 'mani', grams: 15 },
    ],
    steps: [
      'En un bol grande, avena y leche. Microondas 2 min y medio a máxima potencia (se infla: usar bol grande).',
      'Revolver, sumar la banana en rodajas y el maní picado.',
    ],
    prepMinutes: 2,
    cookMinutes: 3,
    storage: { fridgeDays: 0, freezable: false, reheat: 'Se hace en 3 min cada mañana' },
    why: 'Avena y leche: fibra y proteína por menos de $50 el plato.',
  },
  {
    id: 'yogur_avena_manzana',
    name: 'Yogur con avena, manzana y maní',
    slot: 'desayuno',
    appliances: ['sin-coccion'],
    protein: 'lacteo',
    quick: true,
    batch: false,
    ingredients: [
      { id: 'yogur', grams: 200 },
      { id: 'avena', grams: 40 },
      { id: 'manzana', grams: 120 },
      { id: 'mani', grams: 10 },
    ],
    steps: [
      'Yogur en un bol, avena arriba, manzana en cubos y maní. Listo.',
      'Si preferís la avena blanda, armalo la noche anterior en un frasco (overnight oats): aguanta 3 días en la heladera.',
    ],
    prepMinutes: 2,
    cookMinutes: 0,
    storage: { fridgeDays: 0, freezable: false, reheat: 'Se arma en 2 min cada mañana' },
  },
  {
    id: 'panqueques_avena',
    name: 'Panqueques de avena y banana',
    slot: 'desayuno',
    appliances: ['anafe'],
    protein: 'huevo',
    quick: false,
    batch: true,
    ingredients: [
      { id: 'avena', grams: 50 },
      { id: 'huevo', grams: 50 },
      { id: 'banana', grams: 80 },
      { id: 'leche', grams: 60 },
      { id: 'aceite', grams: 3 },
      { id: 'dulce_de_leche', grams: 15 },
    ],
    steps: [
      'Pisar la banana, mezclar con huevo, leche y avena. Dejar reposar 5 min para que espese.',
      'Sartén antiadherente apenas aceitada, fuego medio: cucharones chicos, 2 min por lado. Salen 3 por porción.',
      'Enfriar sobre una rejilla, apilar con papel manteca entre medio y guardar. Dulce de leche al servir.',
    ],
    prepMinutes: 10,
    cookMinutes: 20,
    storage: { fridgeDays: 3, freezable: true, reheat: 'Microondas 40 s (del freezer, 1 min)' },
    why: 'Se hacen el día de cocina y desayunás sin cocinar el resto de la semana.',
  },
  {
    id: 'muffins_banana',
    name: 'Muffins de banana, avena y cocoa al airfryer',
    slot: 'desayuno',
    appliances: ['airfryer'],
    alternatives: { airfryer: 'horno' },
    protein: 'lacteo',
    quick: false,
    batch: true,
    ingredients: [
      { id: 'avena', grams: 35 },
      { id: 'banana', grams: 60 },
      { id: 'huevo', grams: 35 },
      { id: 'harina', grams: 15 },
      { id: 'azucar', grams: 6 },
      { id: 'aceite', grams: 5 },
      { id: 'leche', grams: 25 },
      { id: 'cocoa', grams: 4 },
      { id: 'yogur', grams: 100 },
    ],
    steps: [
      'Pisar las bananas, mezclar con huevo, aceite y leche. Sumar avena, harina, azúcar, cocoa y una pizca de sal.',
      'Repartir en moldes de silicona o pirotines (2 por porción). Airfryer 160 °C, 14 min. En horno: 180 °C, 20 min. Palillo seco = listos.',
      'Enfriar y guardar en un tupper. Se comen con un yogur.',
    ],
    prepMinutes: 10,
    cookMinutes: 15,
    storage: { fridgeDays: 3, freezable: true, reheat: 'Microondas 30 s (del freezer, 50 s)' },
  },
  {
    id: 'tostadas_huevo',
    name: 'Tostadas con huevo revuelto (microondas) y naranja',
    slot: 'desayuno',
    appliances: ['microondas'],
    alternatives: { microondas: 'anafe' },
    protein: 'huevo',
    quick: true,
    batch: false,
    ingredients: [
      { id: 'pan_molde', grams: 60 },
      { id: 'huevo', grams: 100 },
      { id: 'manteca', grams: 5 },
      { id: 'naranja', grams: 150 },
      { id: 'sal', grams: 1 },
    ],
    steps: [
      'Batir 2 huevos con sal en una taza con la manteca. Microondas 45 s, revolver, 30 s más.',
      'Tostar el pan y servir con la naranja.',
    ],
    prepMinutes: 2,
    cookMinutes: 3,
    storage: { fridgeDays: 0, freezable: false, reheat: 'Se hace en 4 min cada mañana' },
  },
  {
    id: 'leche_cocoa_tostadas',
    name: 'Leche con cocoa y tostadas con queso',
    slot: 'desayuno',
    appliances: ['microondas'],
    alternatives: { microondas: 'anafe' },
    protein: 'lacteo',
    quick: true,
    batch: false,
    ingredients: [
      { id: 'leche', grams: 250 },
      { id: 'cocoa', grams: 15 },
      { id: 'pan_molde', grams: 60 },
      { id: 'queso', grams: 30 },
    ],
    steps: [
      'Calentar la leche 1 min y medio en el microondas y disolver la cocoa.',
      'Tostar el pan y poner el queso en fetas.',
    ],
    prepMinutes: 2,
    cookMinutes: 3,
    storage: { fridgeDays: 0, freezable: false, reheat: 'Se hace en 3 min cada mañana' },
  },

  // ═══════════════════════════════ MERIENDAS ════════════════════════════════
  {
    id: 'fruta_mani',
    name: 'Manzana con un puñado de maní',
    slot: 'merienda',
    appliances: ['sin-coccion'],
    protein: 'ninguna',
    quick: true,
    batch: false,
    ingredients: [
      { id: 'manzana', grams: 150 },
      { id: 'mani', grams: 20 },
    ],
    steps: ['Manzana entera y 20 g de maní (dos cucharadas). Va en la mochila.'],
    prepMinutes: 1,
    cookMinutes: 0,
    storage: { fridgeDays: 0, freezable: false, reheat: 'Sin preparación' },
  },
  {
    id: 'yogur_banana',
    name: 'Yogur con banana',
    slot: 'merienda',
    appliances: ['sin-coccion'],
    protein: 'lacteo',
    quick: true,
    batch: false,
    ingredients: [
      { id: 'yogur', grams: 200 },
      { id: 'banana', grams: 100 },
    ],
    steps: ['Un vaso de yogur y una banana. Con mate o té, va igual.'],
    prepMinutes: 1,
    cookMinutes: 0,
    storage: { fridgeDays: 0, freezable: false, reheat: 'Sin preparación' },
  },
  {
    id: 'galletitas_queso',
    name: 'Galletitas al agua con queso y tomate',
    slot: 'merienda',
    appliances: ['sin-coccion'],
    protein: 'lacteo',
    quick: true,
    batch: false,
    ingredients: [
      { id: 'galletitas_agua', grams: 30 },
      { id: 'queso', grams: 30 },
      { id: 'tomate', grams: 60 },
    ],
    steps: ['5 galletitas con queso en fetas y tomate en rodajas.'],
    prepMinutes: 2,
    cookMinutes: 0,
    storage: { fridgeDays: 0, freezable: false, reheat: 'Sin preparación' },
  },
  {
    id: 'tostadas_dulce_leche',
    name: 'Tostadas con dulce de leche y yogur',
    slot: 'merienda',
    appliances: ['sin-coccion'],
    protein: 'lacteo',
    quick: true,
    batch: false,
    ingredients: [
      { id: 'pan_molde', grams: 60 },
      { id: 'dulce_de_leche', grams: 20 },
      { id: 'yogur', grams: 100 },
    ],
    steps: ['Dos tostadas con dulce de leche y medio vaso de yogur.'],
    prepMinutes: 2,
    cookMinutes: 0,
    storage: { fridgeDays: 0, freezable: false, reheat: 'Sin preparación' },
  },
  {
    id: 'sandwich_jamon_queso',
    name: 'Sándwich de jamón y queso con tomate',
    slot: 'merienda',
    appliances: ['sin-coccion'],
    protein: 'lacteo',
    quick: true,
    batch: false,
    ingredients: [
      { id: 'pan_molde', grams: 60 },
      { id: 'jamon_cocido', grams: 30 },
      { id: 'queso', grams: 25 },
      { id: 'tomate', grams: 40 },
    ],
    steps: ['Un sándwich de pan de molde con jamón, queso y tomate. Frío o tostado.'],
    prepMinutes: 2,
    cookMinutes: 0,
    storage: { fridgeDays: 0, freezable: false, reheat: 'Sin preparación' },
  },
])

export const RECIPE_BY_ID: ReadonlyMap<string, Recipe> = new Map(RECIPES.map(r => [r.id, r]))

export function recipeById(id: string): Recipe {
  const recipe = RECIPE_BY_ID.get(id)
  if (!recipe) throw new Error(`Receta desconocida: ${id}`)
  return recipe
}
