// app/utils/moneyApps.ts
// Directory of money/economy apps useful in Uruguay: official banking apps,
// digital wallets & payments, investing/crypto, government/tax, everyday useful
// tools and indie/community projects. PURE data + helpers (no Vue/Nuxt) so the
// page and tests share one source of truth.
//
// Every entry was web-researched and, where uncertain, adversarially checked for
// existence/availability in Uruguay; unconfirmed ones are flagged `verified:false`.
// Not affiliated with any of the listed apps; store availability and features
// change — verify in the official store before downloading. Informational only.

export type AppCategory =
  | 'bancos'
  | 'billeteras_pagos'
  | 'inversiones'
  | 'cripto'
  | 'finanzas_personales'
  | 'gobierno_tramites'
  | 'servicios_utiles'
  | 'comunidad_indie'

export type Platform = 'ios' | 'android' | 'web'

export interface MoneyApp {
  /** kebab-case id, unique across {@link MONEY_APPS}. */
  id: string
  name: string
  category: AppCategory
  /** Company/person/entity that publishes it. */
  developer: string
  platforms: Platform[]
  /** Free to download. */
  free: boolean
  /** true = bank/government/regulated entity; false = indie/community/third-party. */
  official: boolean
  description: string
  /** Official site or a store listing URL. */
  website: string
  androidUrl?: string
  iosUrl?: string
  note?: string
  /** true when existence + availability for Uruguay were confirmed against a source. */
  verified: boolean
}

export const APP_CATEGORIES: Readonly<Record<AppCategory, string>> = Object.freeze({
  bancos: 'Apps de bancos',
  billeteras_pagos: 'Billeteras y pagos',
  inversiones: 'Inversión',
  cripto: 'Criptomonedas',
  finanzas_personales: 'Finanzas personales',
  gobierno_tramites: 'Gobierno y trámites',
  servicios_utiles: 'Servicios útiles',
  comunidad_indie: 'Comunidad e indie',
})

export const APP_CATEGORY_ICONS: Readonly<Record<AppCategory, string>> = Object.freeze({
  bancos: 'mdi-bank-outline',
  billeteras_pagos: 'mdi-wallet-outline',
  inversiones: 'mdi-chart-areaspline',
  cripto: 'mdi-bitcoin',
  finanzas_personales: 'mdi-piggy-bank-outline',
  gobierno_tramites: 'mdi-office-building-outline',
  servicios_utiles: 'mdi-toolbox-outline',
  comunidad_indie: 'mdi-account-group-outline',
})

export const PLATFORM_META: Readonly<Record<Platform, { label: string; icon: string }>> =
  Object.freeze({
    android: { label: 'Android', icon: 'mdi-android' },
    ios: { label: 'iOS', icon: 'mdi-apple' },
    web: { label: 'Web', icon: 'mdi-web' },
  })

export const MONEY_APPS: MoneyApp[] = [
  {
    id: 'cambio-uruguay',
    name: 'Cambio Uruguay',
    category: 'comunidad_indie',
    developer: 'Cambio Uruguay (eduair94)',
    platforms: ['web'],
    free: true,
    official: false,
    description:
      'Comparador en vivo de la cotización del dólar y otras monedas en más de 40 casas de cambio, con histórico, alertas y herramientas. Instalable como app (PWA) desde el navegador.',
    website: 'https://cambio-uruguay.com',
    note: 'Este mismo sitio. Proyecto independiente y open source.',
    verified: true,
  },
  {
    id: 'cambio-uruguay-bots',
    name: 'Cambio Uruguay en Telegram y Discord',
    category: 'comunidad_indie',
    developer: 'Cambio Uruguay (eduair94)',
    platforms: ['web'],
    free: true,
    official: false,
    description:
      'Bots gratuitos que envían la cotización del dólar y alertas de precio directamente a Telegram y Discord, sin instalar nada.',
    website: 'https://cambio-uruguay.com/conectar',
    verified: true,
  },
  {
    id: 'brou-ebrou',
    name: 'App eBROU',
    category: 'bancos',
    developer: 'Banco de la República Oriental del Uruguay (BROU)',
    platforms: ['ios', 'android', 'web'],
    free: true,
    official: true,
    description:
      'App oficial del banco estatal BROU para ver saldos y movimientos, hacer transferencias, pagar servicios (con descuento de IVA vía Multipagos) y recargar celular; es la banca móvil más usada del Uruguay.',
    website: 'https://www.brou.com.uy/personas/app-ebrou',
    androidUrl: 'https://play.google.com/store/apps/details?id=uy.brou',
    iosUrl: 'https://apps.apple.com/uy/app/app-ebrou/id841015703',
    note: 'Complementada por la web e-BROU (home banking). ~2,3M descargas.',
    verified: true,
  },
  {
    id: 'brou-llave-digital',
    name: 'BROU Llave Digital',
    category: 'bancos',
    developer: 'Banco de la República Oriental del Uruguay (BROU)',
    platforms: ['ios', 'android'],
    free: true,
    official: true,
    description:
      'App de segundo factor del BROU que genera códigos de un solo uso (token) para autorizar operaciones y dar seguridad al home banking; no reemplaza a la app eBROU sino que la acompaña.',
    website: 'https://www.brou.com.uy/',
    androidUrl: 'https://play.google.com/store/apps/details?id=uy.com.brou.token',
    iosUrl: 'https://apps.apple.com/uy/app/brou-llave-digital/id1442954236',
    note: 'Herramienta de seguridad (token), no de banca en sí.',
    verified: true,
  },
  {
    id: 'itau-uruguay',
    name: 'Itaú Uruguay',
    category: 'bancos',
    developer: 'Banco Itaú Uruguay S.A.',
    platforms: ['ios', 'android', 'web'],
    free: true,
    official: true,
    description:
      'App oficial de banca personal de Itaú Uruguay para consultar cuentas y tarjetas, transferir, pagar y comprar/vender moneda 24/7 desde el celular.',
    website: 'https://www.itau.com.uy/inst/appItau.html',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.uy.itau.appitauuypf',
    iosUrl: 'https://apps.apple.com/uy/app/ita%C3%BA-uy/id1065572083',
    verified: true,
  },
  {
    id: 'itau-empresas-uruguay',
    name: 'Itaú Empresas Uruguay',
    category: 'bancos',
    developer: 'Banco Itaú Uruguay S.A.',
    platforms: ['ios', 'android'],
    free: true,
    official: true,
    description:
      'App de Itaú Uruguay orientada a clientes empresa para autorizar operaciones con firma y enviar nóminas de pagos a proveedores y sueldos.',
    website: 'https://www.itau.com.uy/',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.uy.itau.appile',
    note: 'Segmento empresas, no banca personal.',
    verified: true,
  },
  {
    id: 'itau-pagos-uruguay',
    name: 'Itaú Pagos Uruguay',
    category: 'bancos',
    developer: 'Banco Itaú Uruguay S.A.',
    platforms: ['ios', 'android'],
    free: true,
    official: true,
    description:
      'App de Itaú Uruguay enfocada en centralizar el pago de cuentas y servicios en un solo lugar.',
    website: 'https://www.itau.com.uy/',
    androidUrl: 'https://play.google.com/store/apps/details?id=uy.com.itau.pagocuentas',
    note: 'App de pagos, complementaria a la de banca.',
    verified: true,
  },
  {
    id: 'santander-uruguay',
    name: 'Santander Uruguay',
    category: 'bancos',
    developer: 'Banco Santander Uruguay',
    platforms: ['ios', 'android', 'web'],
    free: true,
    official: true,
    description:
      'App oficial de banca personal de Santander Uruguay para ver saldos y movimientos, transferir, pagar tarjetas y servicios y gestionar límites de las tarjetas.',
    website: 'https://www.santander.com.uy/',
    androidUrl: 'https://play.google.com/store/apps/details?id=uy.com.Santander',
    iosUrl: 'https://apps.apple.com/uy/app/santander-uruguay/id938240853',
    verified: true,
  },
  {
    id: 'santander-empresas-uruguay',
    name: 'Santander Empresas Uruguay',
    category: 'bancos',
    developer: 'Banco Santander Uruguay',
    platforms: ['android'],
    free: true,
    official: true,
    description:
      'App de Santander Uruguay para el segmento empresas, con operativa y autorizaciones de negocio.',
    website: 'https://www.santander.com.uy/',
    androidUrl: 'https://play.google.com/store/apps/details?id=uy.bancosantander.empresas',
    note: 'Segmento empresas; existe también Santander Inversiones Uruguay.',
    verified: true,
  },
  {
    id: 'bbva-uruguay',
    name: 'BBVA Uruguay',
    category: 'bancos',
    developer: 'BBVA (Banco Bilbao Vizcaya Argentaria Uruguay S.A.)',
    platforms: ['ios', 'android', 'web'],
    free: true,
    official: true,
    description:
      'App oficial de banca personal de BBVA Uruguay para consultar cuentas, transferir, comprar/vender moneda, pagar tarjetas y pagar por QR desde el celular.',
    website: 'https://www.bbva.com.uy/personas.html',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.bbva.glomo.uy',
    iosUrl: 'https://apps.apple.com/uy/app/bbva-uruguay/id1383614279',
    note: 'Existe además Pagos BBVA Uruguay para cobros/pagos comerciales.',
    verified: true,
  },
  {
    id: 'scotiabank-uruguay-scotia-movil',
    name: 'Scotia Móvil (Scotiabank Uruguay)',
    category: 'bancos',
    developer: 'Scotiabank Uruguay',
    platforms: ['ios', 'android', 'web'],
    free: true,
    official: true,
    description:
      'App oficial de Scotiabank Uruguay para transferir entre cuentas y a terceros, consultar saldos y movimientos de cuentas, préstamos y plazos fijos, y ubicar sucursales y cajeros.',
    website: 'https://www.scotiabank.com.uy/Acerca-de/canales-de-atencion/ScotiaMovil',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.ingsw.scotiabankapp',
    iosUrl: 'https://apps.apple.com/uy/app/scotia-m%C3%B3vil/id920063972',
    verified: true,
  },
  {
    id: 'hsbc-uruguay-ibanca',
    name: 'HSBC Uruguay - iBanca',
    category: 'bancos',
    developer: 'HSBC Bank (Uruguay) S.A.',
    platforms: ['ios', 'android', 'web'],
    free: true,
    official: true,
    description:
      'App de banca electrónica iBanca de HSBC Uruguay para gestionar cuentas personales y de empresa, instruir pagos y transferencias, y comprar/vender moneda con acceso biométrico.',
    website: 'https://www.hsbc.com.uy/digital/ibanca-uy/',
    androidUrl: 'https://play.google.com/store/apps/details?id=uy.com.hsbc.hsbcuruguay',
    iosUrl: 'https://apps.apple.com/uy/app/hsbc-uruguay-ibanca/id1497854802',
    note: 'HSBC vendió su banca minorista a Itaú en 2019; hoy opera banca corporativa/premier, pero la app iBanca sigue activa (actualizada 2026).',
    verified: true,
  },
  {
    id: 'bna-mas-uruguay',
    name: 'BNA+ (Banco de la Nación Argentina)',
    category: 'bancos',
    developer: 'Banco de la Nación Argentina',
    platforms: ['ios', 'android'],
    free: true,
    official: true,
    description:
      'App del Banco de la Nación Argentina (que tiene sucursal operando en Uruguay) para consultar saldos, pagar servicios y transferir; su funcionalidad está centrada en clientes de Argentina.',
    website: 'https://www.bna.com.uy/',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.banconacion.bnamas',
    iosUrl: 'https://apps.apple.com/uy/app/bna/id1523383806',
    note: 'El BNA opera en Uruguay como sucursal, pero la app BNA+ es del banco argentino y su operativa está pensada para cuentas de Argentina.',
    verified: true,
  },
  {
    id: 'bandes-ebandes-uruguay',
    name: 'eBandes (Banco Bandes Uruguay)',
    category: 'bancos',
    developer: 'Banco Bandes Uruguay S.A.',
    platforms: ['ios'],
    free: true,
    official: true,
    description:
      'App de banca móvil de Banco Bandes Uruguay para consultar cuentas, ver saldos y movimientos, generar estados y transferir a cuentas Bandes y de otros bancos locales.',
    website: 'https://www.bandesuruguay.com.uy/',
    iosUrl: 'https://apps.apple.com/uy/app/ebandes/id1441463883',
    note: 'Listada en App Store; no confirmé versión oficial en Google Play. Banco Bandes está bajo sanciones del Tesoro de EE.UU. (OFAC) desde 2019, dato de contexto relevante.',
    verified: true,
  },
  {
    id: 'bhu-home-banking',
    name: 'BHU Home Banking / Banca en línea',
    category: 'bancos',
    developer: 'Banco Hipotecario del Uruguay (BHU)',
    platforms: ['web'],
    free: true,
    official: true,
    description:
      'Banca en línea del banco estatal BHU (portal.bhu.net) para consultar cuentas, pagar tarjetas y préstamos y constituir plazos fijos; no confirmé una app móvil oficial propia de BHU Uruguay.',
    website: 'https://www.bhu.com.uy/sobre-bhu/canales-de-atencion',
    note: "La app 'Banca Móvil Banco Hipotecario' (com.hipotecario.mobile) corresponde al Banco Hipotecario S.A. de Argentina, no a BHU Uruguay. BHU ofrece home banking web; no verifiqué app móvil dedicada.",
    verified: false,
  },
  {
    id: 'mercado-pago',
    name: 'Mercado Pago',
    category: 'billeteras_pagos',
    developer: 'Mercado Libre (MELI Uruguay S.R.L.)',
    platforms: ['ios', 'android', 'web'],
    free: true,
    official: true,
    description:
      'Billetera digital y cuenta con tarjeta prepaga/virtual del ecosistema Mercado Libre: pagos con QR, transferencias, pago de servicios y recargas, muy usada en comercios de Uruguay.',
    website: 'https://www.mercadopago.com.uy/',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.mercadopago.wallet',
    iosUrl: 'https://apps.apple.com/uy/app/id925436649',
    note: 'Regulada como institución de dinero electrónico; interopera con QR local.',
    verified: true,
  },
  {
    id: 'prex',
    name: 'Prex Uruguay',
    category: 'billeteras_pagos',
    developer: 'Prex (Prex Holding S.A.S.)',
    platforms: ['ios', 'android'],
    free: true,
    official: true,
    description:
      'Cuenta digital con Mastercard prepaga internacional para pagar, transferir gratis entre usuarios Prex, cobrar BPS/DGI y pagar en el exterior; regulada por el BCU.',
    website: 'https://play.google.com/store/apps/details?id=air.Prex',
    androidUrl: 'https://play.google.com/store/apps/details?id=air.Prex',
    iosUrl: 'https://apps.apple.com/uy/app/id927400689',
    verified: true,
  },
  {
    id: 'midinero',
    name: 'Midinero',
    category: 'billeteras_pagos',
    developer: 'Redpagos (emisor Findarin S.A., regulado por el BCU)',
    platforms: ['ios', 'android'],
    free: true,
    official: true,
    description:
      'Billetera con tarjeta prepaga internacional del grupo Redpagos: consultar saldo, transferir, pagar servicios y retirar la tarjeta en locales Redpagos de todo Uruguay.',
    website: 'https://www.midinero.com.uy/',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.midinero.mobile.myapp',
    iosUrl: 'https://apps.apple.com/uy/app/id1263494371',
    note: 'Pionera en integrar Google Wallet y Apple Pay en Uruguay.',
    verified: true,
  },
  {
    id: 'miredpagos',
    name: 'Miredpagos (app Redpagos)',
    category: 'billeteras_pagos',
    developer: 'Redpagos',
    platforms: ['ios', 'android'],
    free: true,
    official: true,
    description:
      'App de la red Redpagos para pagar más de 1.000 servicios, impuestos y cuotas, recargar saldo y enviar/recibir giros de efectivo; se ingresa con usuario Midinero.',
    website: 'https://web.miredpagos.com.uy/',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.miredpagos.myapp',
    iosUrl: 'https://apps.apple.com/uy/app/id1270893460',
    verified: true,
  },
  {
    id: 'abitab',
    name: 'Abitab',
    category: 'billeteras_pagos',
    developer: 'Abitab S.A.',
    platforms: ['ios', 'android'],
    free: true,
    official: true,
    description:
      'App de la red Abitab para pagar más de 1.000 servicios y facturas, enviar y cobrar giros, gestionar Abitab Locker, estacionamiento tarifado y consultar peaje electrónico.',
    website: 'https://www.abitab.com.uy/',
    androidUrl: 'https://play.google.com/store/apps/details?id=uy.com.abitab.app',
    iosUrl: 'https://apps.apple.com/uy/app/id1111265951',
    note: 'Abitab también publica la app aparte Identidad Digital Abitab.',
    verified: true,
  },
  {
    id: 'paganza',
    name: 'Paganza',
    category: 'billeteras_pagos',
    developer: 'Paganza (fintech uruguaya)',
    platforms: ['ios', 'android'],
    free: true,
    official: false,
    description:
      'App uruguaya para pagar facturas y servicios desde el celular con aviso de vencimientos, y billetera prepaga para enviar dinero a contactos o a cuentas bancarias.',
    website: 'https://www.paganza.com/',
    androidUrl: 'https://play.google.com/store/apps/details?id=paganza.android',
    iosUrl: 'https://apps.apple.com/uy/app/id566320731',
    note: 'Fintech independiente enfocada en pago de cuentas; operativa desde 2012.',
    verified: true,
  },
  {
    id: 'tuapp-antel',
    name: 'tuapp',
    category: 'billeteras_pagos',
    developer: 'Antel (telco estatal)',
    platforms: ['ios', 'android'],
    free: true,
    official: true,
    description:
      'Billetera electrónica de Antel para recargas, pago de servicios (UTE, OSE, Antel, mutualistas), compras con QR y transferencias entre billeteras, asociada a cuenta BROU o tarjetas.',
    website: 'https://www.tuapp.com.uy/',
    androidUrl: 'https://play.google.com/store/apps/details?id=uy.com.antel.bits',
    iosUrl: 'https://apps.apple.com/uy/app/id955003522',
    verified: true,
  },
  {
    id: 'toke',
    name: 'Toke',
    category: 'billeteras_pagos',
    developer: 'Urutec',
    platforms: ['android', 'web'],
    free: true,
    official: true,
    description:
      'Sistema interoperable de pagos con QR en Uruguay que conecta bancos e instituciones de dinero electrónico (BROU, Santander, Itaú, BBVA, Scotiabank, HSBC) para pagar leyendo un QR.',
    website: 'https://toke.uy/',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.popular.pinkapp',
    note: 'Se usa mayormente dentro de la app de cada banco adherido; también existe una app Toke independiente en Google Play.',
    verified: true,
  },
  {
    id: 'plexo',
    name: 'Plexo',
    category: 'billeteras_pagos',
    developer: 'Plexo (Grupo Itaú)',
    platforms: ['web'],
    free: true,
    official: true,
    description:
      'Pasarela y facilitador de pagos B2B con licencia del BCU y certificación PCI DSS que permite a comercios cobrar online con todos los medios de pago; no es una billetera de consumidor.',
    website: 'https://www.plexo.com.uy/',
    note: 'Herramienta para comercios (no tiene app de usuario final en tiendas); adquirida por Itaú.',
    verified: true,
  },
  {
    id: 'sistarbanc',
    name: 'Sistarbanc',
    category: 'billeteras_pagos',
    developer: 'Sistarbanc S.R.L.',
    platforms: ['web'],
    free: true,
    official: true,
    description:
      'Procesadora de pagos regulada por el BCU que opera las transacciones Visa de los bancos uruguayos; su web permite a tarjetahabientes consultar estado de cuenta, pero no es una billetera.',
    website: 'https://www.e-sistarbanc.com.uy/',
    note: 'Infraestructura de procesamiento (B2B), no una app de billetera para el público.',
    verified: true,
  },
  {
    id: 'bandes-billetera',
    name: 'Banco Bandes Uruguay (banca móvil)',
    category: 'billeteras_pagos',
    developer: 'Banco Bandes Uruguay',
    platforms: ['ios', 'android'],
    free: true,
    official: true,
    description:
      'Banco regulado por el BCU con presencia de apps de banca móvil; no pude confirmar una billetera/QR específica de marca Bandes disponible para Uruguay.',
    website: 'https://www.bandes.com.uy/',
    note: "No confirmé una app billetera Bandes de Uruguay en las tiendas; la app 'Bandes' de Google Play (br.com.bandes.mobile) es del banco brasileño BANDES, no de Uruguay.",
    verified: false,
  },
  {
    id: 'google-wallet',
    name: 'Billetera de Google (Google Pay)',
    category: 'billeteras_pagos',
    developer: 'Google LLC',
    platforms: ['android'],
    free: true,
    official: true,
    description:
      'Billetera de pagos contactless (NFC) disponible en Uruguay desde fines de 2024 para pagar con el celular usando tarjetas de bancos y emisores locales adheridos.',
    website: 'https://play.google.com/store/apps/details?id=com.google.android.apps.walletnfcrel',
    androidUrl:
      'https://play.google.com/store/apps/details?id=com.google.android.apps.walletnfcrel',
    note: 'En iPhone el equivalente es Apple Pay, integrado en la app Wallet de Apple (no es app aparte).',
    verified: true,
  },
  {
    id: 'balanz',
    name: 'Balanz',
    category: 'inversiones',
    developer: 'Balanz Capital Valores S.A.U.',
    platforms: ['ios', 'android', 'web'],
    free: true,
    official: true,
    description:
      'Casa de inversion regional que en Uruguay opera como gestora de portafolios regulada por el BCU, con app para invertir en bonos, acciones, CEDEARs y fondos.',
    website: 'https://balanz.com.uy/',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.mobile.balanz.droid',
    iosUrl: 'https://apps.apple.com/uy/app/balanz/id1318206099',
    note: 'Regulada localmente por el BCU (gestora de portafolios).',
    verified: true,
  },
  {
    id: 'santander-inversiones-uy',
    name: 'Santander Inversiones Uruguay',
    category: 'inversiones',
    developer: 'Banco Santander (Uruguay)',
    platforms: ['android'],
    free: true,
    official: true,
    description:
      'App del Banco Santander Uruguay para gestionar inversiones (fondos, bonos, acciones) desde la cuenta local; entidad regulada por el BCU.',
    website: 'https://play.google.com/store/apps/details?id=uy.bancosantander.inversiones',
    androidUrl: 'https://play.google.com/store/apps/details?id=uy.bancosantander.inversiones',
    note: 'Regulada localmente (banco supervisado por el BCU). Solo se confirmo la version Android.',
    verified: true,
  },
  {
    id: 'etoro',
    name: 'eToro',
    category: 'inversiones',
    developer: 'eToro',
    platforms: ['ios', 'android', 'web'],
    free: true,
    official: false,
    description:
      'Plataforma global de trading social para acciones, ETFs y cripto, usada por uruguayos de forma transfronteriza.',
    website: 'https://www.etoro.com/',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.etoro.openbook',
    iosUrl: 'https://apps.apple.com/us/app/etoro-investing-made-social/id674984916',
    note: 'No regulada en Uruguay; opera de forma transfronteriza con licencias en otras jurisdicciones.',
    verified: true,
  },
  {
    id: 'xtb',
    name: 'XTB Online Investing',
    category: 'inversiones',
    developer: 'XTB S.A.',
    platforms: ['ios', 'android', 'web'],
    free: true,
    official: false,
    description:
      'Broker internacional de acciones, ETFs y CFDs con app de inversion usada desde Uruguay de forma transfronteriza.',
    website: 'https://www.xtb.com/',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.xtb.xmobile2',
    note: 'No regulada en Uruguay; broker con licencias en Europa. No se confirmo la URL de App Store.',
    verified: true,
  },
  {
    id: 'gletir-global',
    name: 'Gletir Global',
    category: 'inversiones',
    developer: 'Gletir Corredor de Bolsa S.A.',
    platforms: ['web'],
    free: true,
    official: true,
    description:
      'Corredor de bolsa uruguayo (regulado por el BCU) cuya plataforma Gletir Global permite invertir en mercados internacionales desde una cuenta local.',
    website: 'https://www.gletir.com/GletirGlobal',
    note: 'Regulado localmente por el BCU. No se confirmo app movil dedicada; acceso via plataforma web.',
    verified: true,
  },
  {
    id: 'nobilis',
    name: 'Nobilis',
    category: 'inversiones',
    developer: 'Nobilis (Sociedad de Bolsa)',
    platforms: ['web'],
    free: true,
    official: true,
    description:
      'Corredor de bolsa uruguayo (regulado por el BCU) con plataforma para invertir en instrumentos locales e internacionales.',
    website: 'https://nobilis.com.uy/',
    note: 'Regulado localmente por el BCU. Acceso via plataforma web; no se confirmo app movil dedicada.',
    verified: true,
  },
  {
    id: 'binance',
    name: 'Binance',
    category: 'cripto',
    developer: 'Binance',
    platforms: ['ios', 'android', 'web'],
    free: true,
    official: false,
    description:
      'El mayor exchange de cripto del mundo, ampliamente usado por uruguayos para comprar y vender Bitcoin y otros activos.',
    website: 'https://www.binance.com/',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.binance.dev',
    iosUrl: 'https://apps.apple.com/es/app/binance-compra-bitcoin-crypto/id1436799971',
    note: 'No regulada en Uruguay. Bajo la Ley 20.345 los proveedores de servicios de activos virtuales deben registrarse ante el BCU (en implementacion).',
    verified: true,
  },
  {
    id: 'lemon',
    name: 'Lemon',
    category: 'cripto',
    developer: 'Lemon Cash Inc.',
    platforms: ['ios', 'android'],
    free: true,
    official: false,
    description:
      'Billetera cripto de origen argentino disponible en Uruguay para comprar dolares digitales, cripto y pagar; funciones locales en expansion.',
    website: 'https://lemon.me/',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.applemoncash',
    iosUrl: 'https://apps.apple.com/uy/app/lemon-cash-tu-wallet-crypto/id1499421511',
    note: 'No regulada en Uruguay (Ley 20.345 de activos virtuales en implementacion).',
    verified: true,
  },
  {
    id: 'bitso',
    name: 'Bitso',
    category: 'cripto',
    developer: 'Bitso SAPI de C.V.',
    platforms: ['ios', 'android', 'web'],
    free: true,
    official: false,
    description:
      'Exchange de cripto y acciones disponible en Uruguay para comprar Bitcoin y mas de 150 criptomonedas.',
    website: 'https://bitso.com/',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.bitso.wallet',
    iosUrl: 'https://apps.apple.com/uy/app/bitso-save-and-invest-easily/id1292836438',
    note: 'No regulada en Uruguay (Ley 20.345 en implementacion).',
    verified: true,
  },
  {
    id: 'ripio',
    name: 'Ripio',
    category: 'cripto',
    developer: 'Ripio (BitPagos, Inc.)',
    platforms: ['ios', 'android'],
    free: true,
    official: false,
    description:
      'App cripto latinoamericana disponible en Uruguay para comprar y vender Bitcoin, stablecoins y mas de 100 activos, con tarjeta cripto.',
    website: 'https://www.ripio.com/',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.ripio.android',
    iosUrl: 'https://apps.apple.com/uy/app/ripio-app-crypto-wallet/id1221006761',
    note: 'No regulada en Uruguay (Ley 20.345 en implementacion).',
    verified: true,
  },
  {
    id: 'takenos',
    name: 'Takenos',
    category: 'cripto',
    developer: 'Takenos Inc.',
    platforms: ['ios', 'web'],
    free: true,
    official: false,
    description:
      'Billetera digital de origen argentino para cobrar en dolares/euros del exterior, usada por freelancers uruguayos.',
    website: 'https://takenos.com/',
    iosUrl: 'https://apps.apple.com/ar/app/takenos/id6499217598',
    note: 'No regulada en Uruguay. Fue retirada de Google Play el 31/03/2026; sigue disponible en App Store.',
    verified: true,
  },
  {
    id: 'fiwind',
    name: 'Fiwind',
    category: 'cripto',
    developer: 'FINANCEWIND S.A.',
    platforms: ['ios', 'android'],
    free: true,
    official: false,
    description:
      'Fintech argentina de cripto e inversiones; algunos uruguayos la usan, pero esta orientada al mercado argentino y su disponibilidad plena en Uruguay es limitada.',
    website: 'https://www.fiwind.io/',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.fiwind.app',
    iosUrl: 'https://apps.apple.com/ar/app/fiwind/id1576392007',
    note: 'No regulada en Uruguay; enfocada en Argentina, disponibilidad local no confirmada.',
    verified: false,
  },
  {
    id: 'gub-uy-app',
    name: 'gub.uy',
    category: 'gobierno_tramites',
    developer: 'AGESIC (Agencia de Gobierno Electrónico y Sociedad de la Información)',
    platforms: ['ios', 'android'],
    free: true,
    official: true,
    description:
      'App oficial del Estado uruguayo para iniciar y seguir trámites, recibir avisos de pagos y vencimientos, acceder a documentos digitales y usar la identidad gub.uy que da acceso a servicios como DGI y BPS.',
    website: 'https://play.google.com/store/apps/details?id=uy.gub.app.perfil.release',
    androidUrl: 'https://play.google.com/store/apps/details?id=uy.gub.app.perfil.release',
    iosUrl: 'https://apps.apple.com/uy/app/gub-uy/id1475303589',
    note: 'Puerta de entrada a la identidad digital estatal; se usa para autenticarse en varios servicios de dinero e impuestos.',
    verified: true,
  },
  {
    id: 'dgi-app',
    name: 'DGI',
    category: 'gobierno_tramites',
    developer: 'Dirección General Impositiva (DGI)',
    platforms: ['ios', 'android'],
    free: true,
    official: true,
    description:
      'App oficial de la DGI para personas físicas: permite presentar y pagar declaraciones de IRPF e IVA, consultar posibles devoluciones y ver el historial de declaraciones y pagos.',
    website: 'https://play.google.com/store/apps/details?id=uy.gub.dgi.sd',
    androidUrl: 'https://play.google.com/store/apps/details?id=uy.gub.dgi.sd',
    iosUrl: 'https://apps.apple.com/uy/app/dgi/id1633500680',
    note: 'Requiere identidad digital (Usuario gub.uy, Identidad Mobile Abitab o TuID Antel).',
    verified: true,
  },
  {
    id: 'bps-personas',
    name: 'BPS Personas',
    category: 'gobierno_tramites',
    developer: 'Banco de Previsión Social (BPS)',
    platforms: ['ios', 'android'],
    free: true,
    official: true,
    description:
      'App oficial del BPS para personas: consulta de aportes, recibos de pago de jubilaciones y prestaciones, estado de subsidios por enfermedad o desempleo y actividad laboral.',
    website: 'https://play.google.com/store/apps/details?id=uy.gub.bps.movil.persona',
    androidUrl: 'https://play.google.com/store/apps/details?id=uy.gub.bps.movil.persona',
    iosUrl: 'https://apps.apple.com/us/app/bps-personas/id1511536614',
    note: 'Requiere usuario y contraseña de los servicios en línea del BPS.',
    verified: true,
  },
  {
    id: 'bps-empresas',
    name: 'BPS Empresas',
    category: 'gobierno_tramites',
    developer: 'Banco de Previsión Social (BPS)',
    platforms: ['android'],
    free: true,
    official: true,
    description:
      'App oficial del BPS para empresas: registrar altas y bajas de empleados, consultar facturación y descargar facturas de aportes desde el celular.',
    website: 'https://play.google.com/store/apps/details?id=uy.gub.bps.movil.empresa',
    androidUrl: 'https://play.google.com/store/apps/details?id=uy.gub.bps.movil.empresa',
    note: 'Confirmada en Google Play; no confirmé una versión iOS separada.',
    verified: true,
  },
  {
    id: 'bps-trabajo-domestico',
    name: 'BPS Trabajo Doméstico',
    category: 'gobierno_tramites',
    developer: 'Banco de Previsión Social (BPS)',
    platforms: ['android'],
    free: true,
    official: true,
    description:
      'App oficial del BPS para empleadores de trabajo doméstico: consultar facturación y vencimientos y gestionar altas, bajas y modificaciones del personal.',
    website: 'https://play.google.com/store/apps/details?id=uy.gub.bps.movil.trabajodomestico',
    androidUrl: 'https://play.google.com/store/apps/details?id=uy.gub.bps.movil.trabajodomestico',
    note: 'Confirmada en Google Play; versión iOS no confirmada.',
    verified: true,
  },
  {
    id: 'ute-clientes',
    name: 'UTE Clientes',
    category: 'servicios_utiles',
    developer: 'UTE (Administración Nacional de Usinas y Trasmisiones Eléctricas)',
    platforms: ['ios', 'android'],
    free: true,
    official: true,
    description:
      'App oficial de la eléctrica estatal UTE para ver y pagar la factura de luz, gestionar varias cuentas, informar la lectura del medidor y consultar deudas y consumo.',
    website: 'https://play.google.com/store/apps/details?id=uy.com.ute.customers',
    androidUrl: 'https://play.google.com/store/apps/details?id=uy.com.ute.customers',
    iosUrl: 'https://apps.apple.com/uy/app/ute-clientes/id6472210207',
    note: 'Empresa pública; útil para pago y control de facturas de electricidad.',
    verified: true,
  },
  {
    id: 'mi-antel',
    name: 'Mi Antel',
    category: 'servicios_utiles',
    developer: 'Antel (Administración Nacional de Telecomunicaciones)',
    platforms: ['ios', 'android'],
    free: true,
    official: true,
    description:
      'App oficial de la telefónica estatal Antel para asociar servicios de celular, fijo e internet, consultar saldo y consumo y ver y pagar la factura al vencimiento.',
    website: 'https://play.google.com/store/apps/details?id=uy.com.antel.miantel',
    androidUrl: 'https://play.google.com/store/apps/details?id=uy.com.antel.miantel',
    iosUrl: 'https://apps.apple.com/uy/app/mi-antel/id1335768164',
    note: 'Empresa pública; para pago y control de facturas de telecomunicaciones.',
    verified: true,
  },
  {
    id: 'ose-mi-factura',
    name: 'OSE - Mi Factura',
    category: 'servicios_utiles',
    developer: 'OSE (Obras Sanitarias del Estado)',
    platforms: ['web'],
    free: true,
    official: true,
    description:
      'Servicio web oficial de la estatal del agua OSE para consultar, descargar y pagar la factura de agua en línea; no confirmé una app móvil dedicada, se usa vía portal web y WhatsApp.',
    website: 'https://www.ose.com.uy/clientes/mi-factura',
    note: 'Empresa pública. Es un portal web (más atención por WhatsApp), no una app de tienda confirmada; por eso platforms=web y sin URLs de tienda.',
    verified: true,
  },
  {
    id: 'mi-bse',
    name: 'Mi BSE',
    category: 'servicios_utiles',
    developer: 'BSE (Banco de Seguros del Estado)',
    platforms: ['web'],
    free: true,
    official: true,
    description:
      'Portal web oficial de la aseguradora estatal BSE para gestionar pólizas, pagar cuotas pendientes y denunciar siniestros; no confirmé una app móvil dedicada en las tiendas.',
    website: 'https://mibse.bse.com.uy/',
    note: 'Entidad estatal regulada. Confirmé el portal web Mi BSE; no encontré app oficial en Google Play/App Store, por eso platforms=web.',
    verified: true,
  },
  {
    id: 'como-ir',
    name: 'Cómo Ir',
    category: 'servicios_utiles',
    developer: 'Intendencia de Montevideo (Montevideo DTI)',
    platforms: ['ios', 'android'],
    free: true,
    official: true,
    description:
      'App oficial de la Intendencia de Montevideo para el transporte público: horarios, recorridos, ubicación del ómnibus en tiempo real y consulta de viajes y beneficios de la tarjeta STM.',
    website: 'https://montevideo.gub.uy/',
    androidUrl: 'https://play.google.com/store/apps/details?id=uy.gub.imm.stm.mobile.comoir',
    iosUrl: 'https://apps.apple.com/uy/app/c%C3%B3mo-ir/id933271921',
    note: 'App gubernamental, históricamente criticada por su rendimiento (calificaciones bajas en las tiendas).',
    verified: true,
  },
  {
    id: 'stm-montevideo',
    name: 'STM Montevideo',
    category: 'servicios_utiles',
    developer: 'Matungos (desarrollador independiente)',
    platforms: ['android', 'ios'],
    free: true,
    official: false,
    description:
      'App independiente muy usada para el transporte de Montevideo: horarios, paradas cercanas y qué líneas conectan un punto con otro, como alternativa a la app oficial.',
    website: 'https://play.google.com/store/apps/details?id=com.matungos.stm.mvd',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.matungos.stm.mvd',
    iosUrl: 'https://apps.apple.com/pa/app/stm-montevideo/id938009980',
    note: 'No es oficial de la Intendencia; es un desarrollo de terceros.',
    verified: true,
  },
  {
    id: 'viatik',
    name: 'Viatik',
    category: 'servicios_utiles',
    developer: 'Viatik',
    platforms: ['ios', 'android'],
    free: true,
    official: false,
    description:
      'App uruguaya de movilidad (nacida para viajes compartidos interdepartamentales) que además permite consultar el saldo y recargar la tarjeta STM sin comisión desde el celular.',
    website: 'https://play.google.com/store/apps/details?id=com.viatik.app',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.viatik.app',
    note: 'La recarga STM es de un privado, no del sistema oficial; algunas autoridades han advertido sobre cargar datos en apps no oficiales.',
    verified: true,
  },
  {
    id: 'cabacua',
    name: 'Cabacua',
    category: 'servicios_utiles',
    developer: 'Cabacua',
    platforms: ['android', 'ios', 'web'],
    free: true,
    official: false,
    description:
      'Comparador uruguao de precios de supermercados (y farmacias) en tiempo real: armás un carrito y calcula cuánto costaría esa misma compra en cada cadena.',
    website: 'https://play.google.com/store/apps/details?id=com.cabacua.market',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.cabacua.market',
    note: 'Gratis para el usuario final; monetiza con datos B2B.',
    verified: true,
  },
  {
    id: 'preciosgub',
    name: 'PreciosGub (SIPC)',
    category: 'servicios_utiles',
    developer: 'Área de Defensa del Consumidor / SIPC, Ministerio de Economía y Finanzas',
    platforms: ['android', 'ios', 'web'],
    free: true,
    official: true,
    description:
      'App oficial del Estado (Sistema de Información de Precios al Consumidor) para comparar precios diarios de productos de la canasta básica por establecimiento y con geolocalización.',
    website: 'https://www.precios.uy/',
    androidUrl: 'https://play.google.com/store/apps/details?id=uy.com.bullseye.preciosgub',
    note: 'Datos oficiales reportados por comercios obligados; cubre productos regulados, no todo el surtido.',
    verified: true,
  },
  {
    id: 'pedidosya',
    name: 'PedidosYa (con PedidosYa Plus)',
    category: 'servicios_utiles',
    developer: 'Pedidos Ya S.A. (Delivery Hero)',
    platforms: ['ios', 'android', 'web'],
    free: true,
    official: false,
    description:
      'App de delivery líder en Uruguay cuyo programa de suscripción PedidosYa Plus ofrece envíos gratis ilimitados y descuentos en restaurantes, supermercados y farmacias adheridos.',
    website: 'https://www.pedidosya.com.uy/',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.pedidosya',
    iosUrl: 'https://apps.apple.com/uy/app/pedidosya-delivery-app/id490099807',
    note: 'La app es gratis; PedidosYa Plus es una membresía paga (mínimos de compra para envío gratis en market/farmacias).',
    verified: true,
  },
  {
    id: 'oca-app',
    name: 'OCA App',
    category: 'servicios_utiles',
    developer: 'OCA S.A.',
    platforms: ['ios', 'android', 'web'],
    free: true,
    official: true,
    description:
      'App de la emisora de tarjetas OCA para gestionar la tarjeta y la cuenta OCA Blue, ver estados de cuenta, pagar, y acceder a los descuentos y beneficios diarios en comercios adheridos.',
    website: 'https://oca.uy/',
    androidUrl: 'https://play.google.com/store/apps/details?id=uy.com.oca.ocatarjetas',
    note: 'Los beneficios y el extra 5% al pagar con la app aplican a tarjetas OCA; entidad financiera regulada.',
    verified: true,
  },
  {
    id: 'ahorrin',
    name: 'Ahorrin',
    category: 'finanzas_personales',
    developer: 'Ahorrin (equipo en Montevideo)',
    platforms: ['web'],
    free: true,
    official: false,
    description:
      'Herramienta uruguaya de finanzas personales: subís el estado de cuenta que descargás de tu banco (BROU, Itaú, Santander, BBVA, Scotiabank, etc.) y categoriza tus gastos y presupuesto sin pedir credenciales bancarias.',
    website: 'https://www.ahorrin.app/',
    note: 'Producto web (plan gratis + plan pago); no requiere conectar el banco, se cargan archivos CSV/Excel o datos manuales.',
    verified: true,
  },
  {
    id: 'mobills',
    name: 'Mobills',
    category: 'finanzas_personales',
    developer: 'Mobills Labs',
    platforms: ['ios', 'android', 'web'],
    free: true,
    official: false,
    description:
      'App internacional muy usada en la región para control de gastos, presupuestos y metas de ahorro con carga manual, aplicable en Uruguay al no depender de integración bancaria local.',
    website: 'https://www.mobillsapp.com/',
    note: 'No es una app uruguaya; funciona con carga manual y puede mostrar montos en otra moneda por defecto. No confirmé una disponibilidad/tienda específica para Uruguay.',
    verified: false,
  },
  {
    id: 'socio-espectacular',
    name: 'Socio Espectacular',
    category: 'servicios_utiles',
    developer: 'Socio Espectacular',
    platforms: ['web'],
    free: true,
    official: false,
    description:
      'Programa de socios cultural de Uruguay que, con una cuota mensual, da entradas y descuentos en teatro, cine (Life, Grupocine, Movie, Cinemateca) y otros espectáculos.',
    website: 'https://socioespectacular.com.uy/',
    note: 'No confirmé una app dedicada en las tiendas; los beneficios se gestionan vía la tarjeta de socio y el sitio web.',
    verified: false,
  },
  {
    id: 'club-el-pais',
    name: 'Club El País',
    category: 'servicios_utiles',
    developer: 'El País S.A. (Diario El País)',
    platforms: ['web'],
    free: true,
    official: false,
    description:
      'Programa de beneficios para suscriptores del diario El País, con más de 200 descuentos en gastronomía, tiendas y entretenimiento en todo el país mediante la tarjeta Club El País.',
    website: 'https://www.clubelpais.com.uy/',
    note: 'No confirmé una app dedicada en las tiendas; el acceso a beneficios es por tarjeta/suscripción y sitio web.',
    verified: false,
  },
  {
    id: 'dolar-uruguay-doublebond',
    name: 'Dólar Uruguay',
    category: 'comunidad_indie',
    developer: 'Alejandro Adrián Vázquez Álvarez (DoubleBond)',
    platforms: ['ios', 'android'],
    free: true,
    official: false,
    description:
      'App indie que muestra la cotización del dólar oficial en Uruguay, su evolución histórica y una calculadora USD/UYU; hecha por un desarrollador independiente, no por un banco.',
    website: 'https://play.google.com/store/apps/details?id=com.doublebond.dolaruruguay',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.doublebond.dolaruruguay',
    iosUrl: 'https://apps.apple.com/uy/app/dolar-uruguay/id1447037087',
    note: 'Mismo desarrollador (DoubleBond) publica versiones para otros países; la data del dólar oficial es referencial, no de operación.',
    verified: true,
  },
  {
    id: 'dolar-usa-peso-uruguayo-mallhino',
    name: 'Dólar USA a Peso Uruguayo',
    category: 'comunidad_indie',
    developer: 'Mallhino (desarrollador independiente)',
    platforms: ['android'],
    free: true,
    official: false,
    description:
      'Conversor simple USD↔UYU con la cotización del día, parte de una familia de apps de conversión de monedas hechas por un desarrollador indie; útil para turistas y consultas rápidas en Uruguay.',
    website:
      'https://play.google.com/store/apps/details?id=com.mallhino.us.dollar.to.Uruguayan.peso',
    androidUrl:
      'https://play.google.com/store/apps/details?id=com.mallhino.us.dollar.to.Uruguayan.peso',
    note: 'Es un conversor genérico de tipo de cambio, no una fuente oficial de casas de cambio.',
    verified: true,
  },
  {
    id: 'dolarapi-enzonotario',
    name: 'DolarAPI (esjs-dolar-api)',
    category: 'comunidad_indie',
    developer: 'Enzo Notario',
    platforms: ['web'],
    free: true,
    official: false,
    description:
      'API pública open-source que expone cotizaciones del dólar y otras monedas para varios países incluyendo Uruguay; muy usada por desarrolladores indie para armar sus propias apps de cotización.',
    website: 'https://dolarapi.com',
    note: 'Repo en GitHub (enzonotario/esjs-dolar-api), ~663 estrellas; la cobertura de Uruguay es una de varias del proyecto.',
    verified: true,
  },
  {
    id: 'cotizaciones-brou-gmanrique',
    name: 'cotizaciones-brou',
    category: 'comunidad_indie',
    developer: 'gmanriqueUy (GitHub)',
    platforms: ['web'],
    free: true,
    official: false,
    description:
      'API REST open-source no oficial que devuelve las cotizaciones del BROU (USD, ARS, BRL, EUR) mediante scraping; proyecto comunitario uruguayo alojado en Fly.io.',
    website: 'https://github.com/gmanriqueUy/cotizaciones-brou',
    note: 'No es un producto del BROU; es un wrapper hecho por la comunidad.',
    verified: true,
  },
  {
    id: 'cotizaciones-uruguay-lpbonomi',
    name: 'cotizaciones-uruguay',
    category: 'comunidad_indie',
    developer: 'lpbonomi (GitHub)',
    platforms: ['web'],
    free: true,
    official: false,
    description:
      'Librería open-source en TypeScript/JavaScript que agrega cotizaciones de distintos proveedores uruguayos (BCU y bancos) en una sola interfaz para desarrolladores.',
    website: 'https://github.com/lpbonomi/cotizaciones-uruguay',
    note: 'Herramienta para developers, no una app de usuario final.',
    verified: true,
  },
  {
    id: 'salario-liquido-uruguay-ismaelpadilla',
    name: 'Salario Líquido Uruguay',
    category: 'comunidad_indie',
    developer: 'Ismael Padilla',
    platforms: ['web'],
    free: true,
    official: false,
    description:
      'Calculadora web open-source que estima el salario líquido en Uruguay a partir del nominal, descontando aportes e IRPF; hecha por un desarrollador independiente uruguayo.',
    website: 'https://github.com/ismaelpadilla/salario-liquido-uruguay',
    note: 'Los parámetros de aportes/IRPF deben revisarse cada año.',
    verified: true,
  },
  {
    id: 'econuy-rxavier',
    name: 'econuy',
    category: 'comunidad_indie',
    developer: 'rxavier (Rafael Xavier, GitHub)',
    platforms: ['web'],
    free: true,
    official: false,
    description:
      'Paquete open-source en Python que descarga y ordena datos económicos uruguayos (tipo de cambio, precios, actividad) para análisis; orientado a economistas y developers.',
    website: 'https://github.com/rxavier/econuy',
    note: 'Herramienta de datos económicos, no una app de cotización en vivo.',
    verified: true,
  },
  {
    id: 'wallet-budgetbakers',
    name: 'Wallet: Budget & Money Manager (BudgetBakers)',
    category: 'finanzas_personales',
    developer: 'BudgetBakers',
    platforms: ['ios', 'android'],
    free: true,
    official: false,
    description:
      'App genérica muy usada para registrar gastos, presupuestos y multi-moneda; disponible en Uruguay pero NO es local ni integra bancos uruguayos de forma automática.',
    website: 'https://budgetbakers.com/en/products/wallet/',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.droid4you.application.wallet',
    iosUrl: 'https://apps.apple.com/uy/app/wallet-budget-money-manager/id1032467659',
    note: 'App internacional (checa). Freemium: el sync bancario Premium tiene soporte limitado para bancos de Uruguay; funciona bien en modo manual.',
    verified: true,
  },
  {
    id: 'monefy',
    name: 'Monefy',
    category: 'finanzas_personales',
    developer: 'Reflective Technologies ApS',
    platforms: ['ios', 'android'],
    free: true,
    official: false,
    description:
      'Rastreador de gastos genérico muy popular por su simpleza y registro rápido por categorías; se usa en Uruguay pero no es una app local ni tiene integración bancaria uruguaya.',
    website: 'https://monefy.com/',
    note: 'No confirmé la URL exacta de tienda ni el editor legal; incluida como opción genérica popular, no verificada al detalle.',
    verified: false,
  },
  {
    id: 'fintonic',
    name: 'Fintonic',
    category: 'finanzas_personales',
    developer: 'Fintonic (Spain)',
    platforms: ['ios', 'android'],
    free: true,
    official: false,
    description:
      'Gestor de finanzas personales español ampliamente conocido; se lo menciona como referencia genérica, pero su disponibilidad y agregación bancaria en Uruguay no está confirmada.',
    website: 'https://www.fintonic.com/',
    note: 'No es local. No pude confirmar que opere o agregue bancos en Uruguay; incluida solo como referencia genérica.',
    verified: false,
  },
]

export function platformLabel(p: Platform): string {
  return PLATFORM_META[p].label
}

/** Apps grouped by category, in {@link APP_CATEGORIES} order, dropping empty groups. */
export function moneyAppsByCategory(apps: readonly MoneyApp[] = MONEY_APPS): Array<{
  category: AppCategory
  label: string
  icon: string
  items: MoneyApp[]
}> {
  return (Object.keys(APP_CATEGORIES) as AppCategory[])
    .map(category => ({
      category,
      label: APP_CATEGORIES[category],
      icon: APP_CATEGORY_ICONS[category],
      items: apps.filter(a => a.category === category),
    }))
    .filter(g => g.items.length > 0)
}

export function getMoneyApp(id: string): MoneyApp | undefined {
  return MONEY_APPS.find(a => a.id === id)
}

/** Case/accent-insensitive haystack for the on-page search box. */
export function appHaystack(a: MoneyApp): string {
  return `${a.name} ${a.developer} ${a.description} ${APP_CATEGORIES[a.category]}`
    .toLowerCase()
    .normalize('NFD')
    .replace(/\p{Diacritic}/gu, '')
}
