export const movingServicesEs = {
  title: 'Fletes, mudanzas y armado de muebles en Uruguay',
  description:
    'Directorio de fletes, mudanzas, armadores, guardamuebles y limpieza en Uruguay. Precios publicados, tamaños de camión, cobertura, condiciones y fuentes.',
  intro: 'Compará proveedores, camiones y tarifas para trasladar tus cosas e instalarte.',
  back: 'Alquileres y vivienda',
  directory: 'Directorio',
  guide: 'Cómo comparar',
  sources: 'Fuentes y alcance',
  reviewed: 'Revisión de fuentes',
  snapshot: 'Relevamiento fechado; confirmá precio y disponibilidad antes de contratar.',
  allServices: 'Todos los servicios',
  allDepartments: 'Todo Uruguay',
  search: 'Empresa, localidad o servicio',
  department: 'Departamento',
  service: 'Servicio',
  pricesOnly: 'Con precios publicados',
  vehicleOnly: 'Con medidas o capacidad del vehículo',
  localOnly: 'Sólo con base en el departamento',
  coverageHint:
    'El filtro incluye bases locales, cobertura declarada y empresas que anuncian servicio nacional. Confirmá que atiendan ambas direcciones.',
  reset: 'Limpiar filtros',
  sort: 'Ordenar por',
  sortName: 'Nombre del proveedor',
  sortPriceAsc: 'Precio publicado: menor a mayor',
  sortPriceDesc: 'Precio publicado: mayor a menor',
  sortHint:
    'Los precios se ordenan dentro de cada servicio, moneda y unidad. Los paquetes conservan su importe completo; revisá duración, mínimos, IVA y ayudantes antes de comparar.',
  noComparablePrice: 'Sin tarifa base publicada para este servicio',
  shareSearch: 'Copiar búsqueda',
  shareCopied: 'Enlace copiado',
  shareFallback: 'Copiá este enlace para compartir la búsqueda',
  results: '{shown} de {total} proveedores y servicios',
  countPrices: '{count} con algún precio publicado',
  emptyTitle: 'No hay coincidencias con estos filtros',
  empty:
    'Probá otro servicio o quitá el filtro de precios. Sin resultados no significa que no haya proveedores en la zona.',
  original: 'Las descripciones y condiciones de las fuentes se conservan en español.',
  based: 'Base',
  coverage: 'Cobertura publicada',
  national: 'Anuncia cobertura nacional',
  unknownArea: 'Alcance a confirmar',
  vehicle: 'Vehículo publicado',
  noVehicle: 'Medidas y capacidad sin publicar',
  prices: 'Tarifas publicadas',
  searchTariffs: 'Buscar en estas tarifas',
  quote: 'Requiere presupuesto',
  quoteHint: 'No encontramos una tarifa pública con unidad y alcance identificables.',
  priceCount: '{count} tarifas · ver condiciones',
  details: 'Servicios, tarifas y fuentes',
  website: 'Ver fuente del proveedor',
  phone: 'Llamar',
  whatsapp: 'WhatsApp',
  email: 'Correo',
  source: 'Fuente',
  published: 'Fecha publicada',
  undated: 'Tarifa sin fecha de vigencia publicada',
  minimum: 'Mínimo',
  includes: 'Incluye',
  excludes: 'No incluye',
  conditions: 'Condiciones',
  notes: 'Antes de coordinar',
  from: 'Desde',
  amount: 'Precio',
  priceService: 'Servicio y alcance',
  loadMore: 'Mostrar más proveedores',
  sourceMore: 'Ver todas las fuentes consultadas',
  morePrices: 'Ver las {count} tarifas',
  stale:
    'Esta revisión tiene más de 90 días. Los datos pueden haber cambiado; consultá las fuentes.',
  methodTitle: 'Qué contiene este directorio',
  method:
    'Reúne páginas de proveedores, tarifarios, listados públicos de comercios y servicios municipales. Cada ficha enlaza su evidencia. La revisión comprueba lo que se publicó; no acredita calidad, habilitación, seguro ni disponibilidad. Las afirmaciones de servicio pertenecen a quien las publica.',
  methodology:
    'Las empresas se agrupan cuando comparten identidad y contacto comercial. Los anuncios genéricos de Marketplace y Mercado Libre sirven para descubrir opciones, pero sus importes sin unidad ni condiciones no se convierten en tarifas. Los portales de inmuebles no prueban quién presta una mudanza.',
  coverageMethod:
    'El relevamiento cubre proveedores locales y de alcance nacional, con más evidencia en Montevideo, Canelones y Maldonado. La presencia de una empresa nacional no prueba que haya una base local en cada departamento. No es un censo exhaustivo.',
  priceMethod:
    'La fecha de consulta no es la fecha de vigencia. Se conservan las monedas originales, los mínimos y los adicionales conocidos. “Sin publicar” significa que no encontramos el dato; un precio de cero sólo aparece cuando la fuente dice que el servicio es gratuito.',
  compareTitle: 'Pedí presupuestos que incluyan lo mismo',
  compareIntro:
    'Una hora de camión con chofer no equivale a una hora con dos ayudantes. Un envío por mueble tampoco cubre necesariamente cargarlo, subirlo y armarlo. Usá estas preguntas para comparar propuestas.',
  checklist: [
    {
      title: 'Origen, destino y accesos',
      text: 'Pasá ambas direcciones, fecha, pisos, ascensor, distancia de la puerta al camión y horarios permitidos del edificio.',
    },
    {
      title: 'Inventario y camión',
      text: 'Enumerá bultos y muebles, mandá sus medidas y consultá las medidas interiores útiles del vehículo. Largo, volumen y carga máxima son datos distintos.',
    },
    {
      title: 'Tiempo y personas',
      text: 'Confirmá cuándo empieza a correr la hora, el mínimo, cómo cobran fracciones, cuántos ayudantes vienen y si el chofer también carga.',
    },
    {
      title: 'Total y adicionales',
      text: 'Pedí un total escrito con IVA, traslados, peajes, espera, escaleras, elevación, embalaje y posibles viajes adicionales.',
    },
    {
      title: 'Armado e instalaciones',
      text: 'Aclará qué se desarma y rearma, si se amura y si retiran e instalan equipos. En tiendas, verificá si el armado sólo vale para muebles comprados allí.',
    },
    {
      title: 'Cuidado y coordinación',
      text: 'Consultá protección de muebles, alcance del seguro si lo ofrecen, responsabilidad por daños, seña, cancelación y recibo. Reservá también limpieza y entrega de llaves.',
    },
  ],
  nextTitle: 'Completá tu mudanza',
  paperwork: 'Gastos, UTE, OSE y entrega de llaves',
  furnish: 'Precios para equipar la casa',
  units: {
    hour: 'hora',
    trip: 'viaje',
    km: 'km',
    item: 'artículo',
    month: 'mes',
    m2: 'm²',
    service: 'servicio',
  },
  categories: {
    moving: 'Mudanzas',
    freight: 'Fletes',
    assembly: 'Armado de muebles',
    packing: 'Embalaje',
    storage: 'Guardamuebles',
    cleaning: 'Limpieza',
    removal: 'Retiro de muebles',
    installation: 'Instalaciones',
  },
}

export type MovingServicesCopy = typeof movingServicesEs
const movingServicesEn: MovingServicesCopy = {
  title: 'Moving, freight and furniture assembly in Uruguay',
  description:
    'Directory of movers, freight services, furniture assemblers, storage and cleaning in Uruguay. Published prices, truck sizes, coverage, conditions and sources.',
  intro:
    'Find someone to move your belongings and help you settle in. Compare the service you need, published vehicle dimensions and what each rate includes.',
  back: 'Rentals and housing',
  directory: 'Directory',
  guide: 'How to compare',
  sources: 'Sources and scope',
  reviewed: 'Sources reviewed',
  snapshot: 'Dated research; confirm price and availability before booking.',
  allServices: 'All services',
  allDepartments: 'All Uruguay',
  search: 'Company, town or service',
  department: 'Department',
  service: 'Service',
  pricesOnly: 'Published prices',
  vehicleOnly: 'Vehicle dimensions or capacity available',
  localOnly: 'Only based in this department',
  coverageHint:
    'The filter includes local bases, declared coverage and providers advertising nationwide service. Confirm both addresses are covered.',
  reset: 'Clear filters',
  sort: 'Sort by',
  sortName: 'Provider name',
  sortPriceAsc: 'Published price: low to high',
  sortPriceDesc: 'Published price: high to low',
  sortHint:
    'Prices are sorted within each service, currency and unit. Packages retain their full amount; compare duration, minimums, tax and helpers before choosing.',
  noComparablePrice: 'No published base price for this service',
  shareSearch: 'Copy search link',
  shareCopied: 'Link copied',
  shareFallback: 'Copy this link to share the search',
  results: '{shown} of {total} providers and services',
  countPrices: '{count} with at least one published price',
  emptyTitle: 'No matches for these filters',
  empty:
    'Try another service or remove the price filter. No results does not mean there are no providers in the area.',
  original: 'Source descriptions and conditions are retained in Spanish.',
  based: 'Base',
  coverage: 'Published coverage',
  national: 'Advertises nationwide coverage',
  unknownArea: 'Confirm service area',
  vehicle: 'Published vehicle',
  noVehicle: 'Dimensions and capacity not published',
  prices: 'Published rates',
  searchTariffs: 'Search these rates',
  quote: 'Request a quote',
  quoteHint: 'We found no public rate with an identifiable unit and scope.',
  priceCount: '{count} rates · see conditions',
  details: 'Services, rates and sources',
  website: 'View provider source',
  phone: 'Call',
  whatsapp: 'WhatsApp',
  email: 'Email',
  source: 'Source',
  published: 'Published date',
  undated: 'No published validity date',
  minimum: 'Minimum',
  includes: 'Includes',
  excludes: 'Excludes',
  conditions: 'Conditions',
  notes: 'Before booking',
  from: 'From',
  amount: 'Price',
  priceService: 'Service and scope',
  loadMore: 'Show more providers',
  sourceMore: 'View all sources consulted',
  morePrices: 'View all {count} rates',
  stale: 'This review is over 90 days old. Details may have changed; check the sources.',
  methodTitle: 'What this directory contains',
  method:
    'Provider websites, rate lists, public retailer directories and municipal services. Each entry links to its evidence. Reviewing a source checks what was published; it does not certify quality, licensing, insurance or availability. Service claims belong to their publishers.',
  methodology:
    'Companies are grouped when identity and business contact match. Generic Marketplace and Mercado Libre listings help discover options, but amounts without units and conditions are not treated as rates. Property portals do not establish who provides moving services.',
  coverageMethod:
    'The research includes local and nationwide providers, with stronger evidence in Montevideo, Canelones and Maldonado. Nationwide coverage does not establish a local base in each department. This is not an exhaustive census.',
  priceMethod:
    'The access date is not the validity date. Original currencies, minimums and known extras are retained. “Not published” means we did not find the information; zero is used only when the source explicitly offers a free service.',
  compareTitle: 'Request quotes covering the same work',
  compareIntro:
    'An hour with a driver is different from an hour with two movers. Delivery per item may not include loading, carrying upstairs or assembly. Use these questions to compare quotes.',
  checklist: [
    {
      title: 'Addresses and access',
      text: 'Provide both addresses, date, floors, elevator access, distance from door to truck and building time restrictions.',
    },
    {
      title: 'Inventory and truck',
      text: 'List boxes and furniture with dimensions. Ask for usable internal vehicle dimensions. Length, volume and maximum load are different measurements.',
    },
    {
      title: 'Time and crew',
      text: 'Confirm when billing starts, minimum hours, rounding, number of movers and whether the driver helps carry items.',
    },
    {
      title: 'Total and extras',
      text: 'Request a written total covering VAT, travel, tolls, waiting, stairs, hoisting, packing and extra trips.',
    },
    {
      title: 'Assembly and installations',
      text: 'Specify disassembly, reassembly, wall mounting and appliance removal/installation. Retail assembly may apply only to purchases from that store.',
    },
    {
      title: 'Care and scheduling',
      text: 'Ask about furniture protection, any insurance coverage, damage liability, deposit, cancellation and receipt. Coordinate cleaning and key handover.',
    },
  ],
  nextTitle: 'Complete your move',
  paperwork: 'Bills, UTE, OSE and key handover',
  furnish: 'Prices for furnishing your home',
  units: {
    hour: 'hour',
    trip: 'trip',
    km: 'km',
    item: 'item',
    month: 'month',
    m2: 'm²',
    service: 'service',
  },
  categories: {
    moving: 'Moving',
    freight: 'Freight',
    assembly: 'Furniture assembly',
    packing: 'Packing',
    storage: 'Storage',
    cleaning: 'Cleaning',
    removal: 'Furniture removal',
    installation: 'Installations',
  },
}
const movingServicesPt: MovingServicesCopy = {
  title: 'Fretes, mudanças e montagem de móveis no Uruguai',
  description:
    'Diretório de fretes, mudanças, montadores, guarda-móveis e limpeza no Uruguai. Preços publicados, tamanhos de caminhão, cobertura, condições e fontes.',
  intro:
    'Encontre quem transporta suas coisas e ajuda você a se instalar. Compare o serviço necessário, as medidas publicadas do veículo e o que cada tarifa inclui.',
  back: 'Aluguéis e moradia',
  directory: 'Diretório',
  guide: 'Como comparar',
  sources: 'Fontes e alcance',
  reviewed: 'Fontes revisadas',
  snapshot: 'Pesquisa datada; confirme preço e disponibilidade antes de contratar.',
  allServices: 'Todos os serviços',
  allDepartments: 'Todo o Uruguai',
  search: 'Empresa, localidade ou serviço',
  department: 'Departamento',
  service: 'Serviço',
  pricesOnly: 'Com preços publicados',
  vehicleOnly: 'Com medidas ou capacidade do veículo',
  localOnly: 'Somente com base no departamento',
  coverageHint:
    'O filtro inclui bases locais, cobertura declarada e empresas que anunciam serviço nacional. Confirme o atendimento dos dois endereços.',
  reset: 'Limpar filtros',
  sort: 'Ordenar por',
  sortName: 'Nome do prestador',
  sortPriceAsc: 'Preço publicado: menor a maior',
  sortPriceDesc: 'Preço publicado: maior a menor',
  sortHint:
    'Os preços são ordenados dentro de cada serviço, moeda e unidade. Os pacotes mantêm o valor completo; compare duração, mínimos, impostos e ajudantes.',
  noComparablePrice: 'Sem preço base publicado para este serviço',
  shareSearch: 'Copiar busca',
  shareCopied: 'Link copiado',
  shareFallback: 'Copie este link para compartilhar a busca',
  results: '{shown} de {total} fornecedores e serviços',
  countPrices: '{count} com algum preço publicado',
  emptyTitle: 'Nenhum resultado com estes filtros',
  empty:
    'Tente outro serviço ou retire o filtro de preços. Nenhum resultado não significa ausência de fornecedores na região.',
  original: 'As descrições e condições das fontes são mantidas em espanhol.',
  based: 'Base',
  coverage: 'Cobertura publicada',
  national: 'Anuncia cobertura nacional',
  unknownArea: 'Confirmar área de atendimento',
  vehicle: 'Veículo publicado',
  noVehicle: 'Medidas e capacidade não publicadas',
  prices: 'Tarifas publicadas',
  searchTariffs: 'Buscar nestas tarifas',
  quote: 'Solicitar orçamento',
  quoteHint: 'Não encontramos tarifa pública com unidade e alcance identificáveis.',
  priceCount: '{count} tarifas · veja as condições',
  details: 'Serviços, tarifas e fontes',
  website: 'Ver fonte do fornecedor',
  phone: 'Ligar',
  whatsapp: 'WhatsApp',
  email: 'E-mail',
  source: 'Fonte',
  published: 'Data publicada',
  undated: 'Sem data de vigência publicada',
  minimum: 'Mínimo',
  includes: 'Inclui',
  excludes: 'Não inclui',
  conditions: 'Condições',
  notes: 'Antes de agendar',
  from: 'A partir de',
  amount: 'Preço',
  priceService: 'Serviço e alcance',
  loadMore: 'Mostrar mais fornecedores',
  sourceMore: 'Ver todas as fontes consultadas',
  morePrices: 'Ver as {count} tarifas',
  stale: 'Esta revisão tem mais de 90 dias. Os dados podem ter mudado; consulte as fontes.',
  methodTitle: 'O que este diretório contém',
  method:
    'Sites de fornecedores, tabelas de preços, listas públicas de lojas e serviços municipais. Cada ficha aponta sua evidência. A revisão verifica o que foi publicado; não certifica qualidade, habilitação, seguro ou disponibilidade. As alegações de serviço pertencem a quem as publica.',
  methodology:
    'Empresas são agrupadas quando compartilham identidade e contato comercial. Anúncios genéricos do Marketplace e Mercado Libre ajudam a descobrir opções, mas valores sem unidade e condições não são tratados como tarifas. Portais imobiliários não comprovam quem faz uma mudança.',
  coverageMethod:
    'A pesquisa inclui fornecedores locais e nacionais, com mais evidências em Montevideo, Canelones e Maldonado. Cobertura nacional não comprova base local em cada departamento. Não é um censo exaustivo.',
  priceMethod:
    'A data de consulta não é a data de vigência. São mantidas moedas originais, mínimos e adicionais conhecidos. “Não publicado” significa que não encontramos o dado; zero só aparece quando a fonte oferece expressamente um serviço gratuito.',
  compareTitle: 'Peça orçamentos para o mesmo trabalho',
  compareIntro:
    'Uma hora de caminhão com motorista difere de uma hora com dois ajudantes. Envio por móvel pode não incluir carregar, subir e montar. Use estas perguntas para comparar propostas.',
  checklist: [
    {
      title: 'Endereços e acessos',
      text: 'Informe origem, destino, data, andares, elevador, distância entre porta e caminhão e horários permitidos pelo prédio.',
    },
    {
      title: 'Inventário e caminhão',
      text: 'Liste volumes e móveis com suas medidas. Consulte as dimensões internas úteis do veículo. Comprimento, volume e carga máxima são dados diferentes.',
    },
    {
      title: 'Tempo e equipe',
      text: 'Confirme quando a cobrança começa, o mínimo, o arredondamento, quantos ajudantes vêm e se o motorista também carrega.',
    },
    {
      title: 'Total e adicionais',
      text: 'Peça total por escrito com IVA, deslocamentos, pedágios, espera, escadas, içamento, embalagem e viagens adicionais.',
    },
    {
      title: 'Montagem e instalações',
      text: 'Especifique desmontagem, remontagem, fixação e retirada/instalação de equipamentos. Nas lojas, verifique se a montagem depende de comprar o móvel ali.',
    },
    {
      title: 'Cuidados e coordenação',
      text: 'Consulte proteção, cobertura de seguro quando oferecido, danos, sinal, cancelamento e recibo. Coordene também limpeza e entrega de chaves.',
    },
  ],
  nextTitle: 'Complete sua mudança',
  paperwork: 'Contas, UTE, OSE e entrega de chaves',
  furnish: 'Preços para mobiliar a casa',
  units: {
    hour: 'hora',
    trip: 'viagem',
    km: 'km',
    item: 'artigo',
    month: 'mês',
    m2: 'm²',
    service: 'serviço',
  },
  categories: {
    moving: 'Mudanças',
    freight: 'Fretes',
    assembly: 'Montagem de móveis',
    packing: 'Embalagem',
    storage: 'Guarda-móveis',
    cleaning: 'Limpeza',
    removal: 'Retirada de móveis',
    installation: 'Instalações',
  },
}
export const movingServicesCopy = (locale: string): MovingServicesCopy =>
  locale === 'en' ? movingServicesEn : locale === 'pt' ? movingServicesPt : movingServicesEs
