import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { runInNewContext } from 'node:vm'
import ts from 'typescript'
import mongoose from 'mongoose'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import * as rentals from '../../utils/rentals'
import { rentalPublicPropertyProjection } from '../../server/utils/rentalDetail'

type Stage = Record<string, any>
const route = readFileSync(join(__dirname, '../../server/api/rentals/index.get.ts'), 'utf8')
const compiled = ts.transpileModule(route, {
  compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 },
}).outputText

/** Execute the actual endpoint with IO stubs, retaining its exact Mongo pipelines. */
async function capture(query: Record<string, string> = {}, total = 240) {
  const pipelines: Stage[][] = []
  const dependencies: Record<string, unknown> = {
    '../../models/RentalListing': {
      RentalListingModel: {
        aggregate: (pipeline: Stage[]) => {
          pipelines.push(pipeline)
          return {
            collation: () =>
              Promise.resolve(
                pipeline.some(stage => stage.$count)
                  ? [{ total }]
                  : pipeline.some(stage => stage.$facet)
                    ? [{}]
                    : []
              ),
          }
        },
      },
    },
    '../../models/RentalMeta': {
      RentalMetaModel: {
        findOne: () => ({ select: () => ({ lean: async () => ({ usdUyu: 40 }) }) }),
      },
    },
    '../../utils/db': { connectDb: async () => {} },
    '../../utils/rentalCoverage': { getRentalCoverage: async () => [] },
    '../../utils/rentalDetail': { rentalPublicPropertyProjection },
    '../../utils/rentalAvailability': {
      loadRentalAvailabilityIndex: async () => ({ excludedAdvertIds: () => [] }),
      annotateRentalAvailability: (property: unknown) => property,
    },
    '../../../utils/rentals': rentals,
  }
  const module = { exports: {} as { default?: (event: unknown) => Promise<unknown> } }
  runInNewContext(compiled, {
    exports: module.exports,
    module,
    require: (id: string) => {
      if (!(id in dependencies)) throw new Error(`Unexpected route dependency: ${id}`)
      return dependencies[id]
    },
    defineEventHandler: (handler: unknown) => handler,
    setResponseHeader: () => {},
    getQuery: () => query,
    createError: ({ statusMessage }: { statusMessage: string }) => new Error(statusMessage),
    console,
  })
  await module.exports.default!({})
  return { items: pipelines[0]!, median: pipelines.at(-1)! }
}

describe('rental endpoint sort input', () => {
  it.each(['precio', 'precio-desc', 'metros', 'recientes'])(
    'retains every %s sort key while removing private evidence before buffering',
    async sort => {
      const { items, median } = await capture({ sort, source: 'casasweb' })
      for (const pipeline of [items, median]) {
        const projection = pipeline.findIndex(stage => stage.$project)
        expect(projection).toBeGreaterThanOrEqual(0)
        expect(projection).toBeLessThan(pipeline.findIndex(stage => stage.$sort))
      }
      const projection = items.find(stage => stage.$project)!.$project
      for (const key of Object.keys(rentals.rentalMongoSort(sort as rentals.RentalSort)))
        expect(projection[key]).toBe(1)
      expect(projection).toEqual(rentalPublicPropertyProjection)
      expect(median.find(stage => stage.$project)!.$project).toEqual({ _id: 0, priceUyu: 1 })
    }
  )
})

// Deliberately exercise the 100MiB boundary only on a developer's isolated localhost Mongo.
// The source documents are generated by $documents/$unwind: no database writes or indexes.
const uri = process.env.RENTALS_SORT_TEST_MONGO_URI
describe.skipIf(!uri)('real Mongo rental sort memory regression', () => {
  let client: mongoose.mongo.MongoClient
  const date = new Date().toISOString()
  beforeAll(async () => {
    if (!/^mongodb:\/\/(?:127\.0\.0\.1|localhost):\d+\//.test(uri || ''))
      throw new Error('Sort memory regression requires an isolated localhost Mongo URI')
    client = new mongoose.mongo.MongoClient(uri!)
    await client.connect()
  })
  afterAll(async () => client?.close())
  const fixtures = (count: number): Stage[] => {
    const offer = (source: string, offset: number) => ({
      source,
      listingId: { $concat: [source, ':', { $toString: '$i' }] },
      title: 'Alquiler mensual sintético',
      price: { $add: [10000, '$i', offset] },
      priceUyu: { $add: [10000, '$i', offset] },
      currency: 'UYU',
      lastSeen: date,
      firstSeen: date,
      commonExpenses: 100,
      commonExpensesCurrency: 'UYU',
      identity: { version: 1, description: '$seed' },
      details: { description: '$seed', images: ['$seed'] },
    })
    return [
      { $documents: [{ seed: 'PRIVATE-'.repeat(40000) }] },
      { $set: { i: { $range: [0, count] } } },
      { $unwind: '$i' },
      {
        $project: {
          _id: 0,
          key: { $concat: ['qa-', { $toString: '$i' }] },
          title: 'Synthetic home',
          propertyType: 'apartamento',
          department: 'Montevideo',
          neighborhood: 'Cordón',
          lastSeen: date,
          firstSeen: date,
          freshAt: date,
          area: { $add: [40, '$i'] },
          offers: [offer('infocasas', 0), offer('casasweb', 2000)],
        },
      },
    ]
  }
  const execute = (count: number, pipeline: Stage[]) =>
    client
      .db()
      .aggregate([...fixtures(count), ...pipeline], {
        allowDiskUse: false,
        collation: rentals.RENTAL_COLLATION,
        maxTimeMS: 30000,
      })
      .toArray()

  it('reproduces Mongo error292 when the same endpoint projection is delayed until after sort', async () => {
    const pipelines = await capture({ sort: 'precio', page: '5', perPage: '24' })
    for (const pipeline of [pipelines.items, pipelines.median]) {
      const old = [
        ...pipeline.filter(stage => !stage.$project),
        pipeline.find(stage => stage.$project)!,
      ]
      await expect(execute(240, old)).rejects.toMatchObject({ code: 292 })
    }
  })

  it.each([239, 240])('keeps the exact %i-home median with no disk spill', async count => {
    for (const source of ['', 'casasweb']) {
      const { median } = await capture({ source }, count)
      const middle = await execute(count, median)
      expect(middle.every(row => Object.keys(row).join() === 'priceUyu')).toBe(true)
      const actual = Math.round(middle.reduce((sum, row) => sum + row.priceUyu, 0) / middle.length)
      expect(actual).toBe(Math.round((source ? 12000 : 10000) + (count - 1) / 2))
    }
  })

  it.each(['precio', 'precio-desc', 'metros', 'recientes'])(
    'keeps %s deep pages and same-advert prices exact without sorting private text',
    async sort => {
      const { items } = await capture({ sort, page: '5', perPage: '24', source: 'casasweb' })
      const rows = await execute(240, items)
      const fields = Object.entries(rentals.rentalMongoSort(sort as rentals.RentalSort))
      const oracle = Array.from({ length: 240 }, (_, i) => ({
        key: `qa-${i}`,
        priceUyu: 12000 + i,
        area: 40 + i,
        freshAt: date,
      })).sort((a, b) => {
        for (const [key, direction] of fields) {
          const x = a[key as keyof typeof a],
            y = b[key as keyof typeof b]
          const difference =
            typeof x === 'number' && typeof y === 'number'
              ? x - y
              : String(x).localeCompare(String(y), 'es')
          if (difference) return difference * direction
        }
        return 0
      })
      expect(rows.map(row => row.key)).toEqual(oracle.slice(96, 120).map(row => row.key))
      expect(
        rows.every(
          row =>
            row.matchingOffer.source === 'casasweb' && row.priceUyu === row.matchingOffer.priceUyu
        )
      ).toBe(true)
      expect(JSON.stringify(rows)).not.toMatch(/PRIVATE-|identity|details/)
    }
  )
})
